### ISSUE TITLE
New-ACMECertificate -Generate generate unencrypted key files

### ISSUE THREAD

**Issue by elupus** [ebekker/ACMESharp#109]
Using New-ACMECertificate with -Generate then Submit-ACMECertificate stores key files without the encrypted flag in filesystem.

While using New-ACMECertificate with key and csr files stores them encrypted in the vault.

Compare:
https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.POSH/NewCertificate.cs#L273

To:
https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.POSH/SubmitCertificate.cs#L95

**Comment by ebekker** [comment]
I believe the merge has addressed the flag and the bug that was there when importing Key + CSR.
