### ISSUE TITLE
Compatiblitiy with more versions of PowerShell and .NET

### ISSUE THREAD

**Issue by ebekker** [ebekker/ACMESharp#11]
As per this [comment](https://github.com/ebekker/letsencrypt-win/issues/10#issuecomment-152629902) it would be nice to support more versions of PowerShell and the .NET framework.

Currently, le-win is being developed on PowerShell 4 which is available by default for Win2012R2 and Win 8.1.  This also implies a requirement for .NET 4.5.

PowerShell and .NET compatibility requirements are found [here](https://technet.microsoft.com/en-us/%5Clibrary/hh847769.aspx).

**Comment by Lone-Coder** [comment]
Just to be clear, I was mistaken on the .net framework version being the problem. It wasn't a real blocker for me.

**Comment by ebekker** [comment]
That's good news, just to be clear, what was the issue?  And what platform combination are you running on.

I also did some more digging and PS 4 actually runs on .NET 4 (not 4.5 or later), so that's the minimum that's needed.

**Comment by Lone-Coder** [comment]
The dll was being blocked by windows because I downloaded it from the internet. I was on Server 2012 (not sure if it's R2) and downloaded the zip file from appveyor.com using internet explorer. I had to go unblock it like this:

![](https://cloud.githubusercontent.com/assets/920120/10856360/d58cb98a-7f0c-11e5-9d84-2dfee7543ac3.png)

**Comment by ebekker** [comment]
Thanks, I'll incorporate this as a note when I update the usage instructions wiki.

**Comment by ebekker** [comment]
This was completed as part of the change for cleaning up the providers model.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.
