### ISSUE TITLE
New-ACMEIdentifier - InvalidData 

### ISSUE THREAD

**Issue by yoruNoTsuki** [ebekker/ACMESharp#110]
Hello,

I'm trying to generate a certificate on a aws machine, and I don't understand the error.
**PS> New-ACMEIdentifier -Dns ec2-176-34-XXX-170.eu-west-1.compute.amazonaws.com -Alias 

> ec2-176-34-XXX-170.eu-west-1.compute.amazonaws.com_Alias**
> New-ACMEIdentifier : Error creating new authz :: Policy forbids issuing for nameAt line:1 char:1
> + New-ACMEIdentifier -Dns ec2-176-34-XXX-170.eu-west-1.compute.amazonaw ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (ACMESharp.Vault.Model.IdentifierInfo:IdentifierInfo) [New-ACMEIdentifier],
>     AcmeWebException
>     + FullyQualifiedErrorId : urn:acme:error:malformed (400),ACMESharp.POSH.NewIdentifier

For information, this command works:
**New-ACMEIdentifier -Dns ec2-176-34-XXX-170.eu-west-1.compute.testtesttesttesttesttest.com -Alias ec2-176-34-XXX-170.eu-west-1.compute.testtesttesttesttesttest.com_Alias**
(XXX is to replace by a correct number)

Can't I generate a certificate on an amazon machine? Is it the limit of domain certificate by week?
Can you help me with the problem?

**Comment by bseddon** [comment]
I generate certificates on an EC2 instance.   The problem you have is that 'compute.amazonaws.com' is blacklisted by the Let's Encrypt servers.  You don't own it or any sub-domain so it appears that you are someone who is at risk of using an Amazon AWS domain for hacking.  I'm not saying you are, just that this is the reason the domain is blocked.

If you want to generate a certificate you will need to use a domain you do own. When you own a domain you will be able to created CNAME record in the DNS record set for the domain that references the AWS domain.  Or just create an A record that points to the IP address 176.34.xxx.170.

**Comment by yoruNoTsuki** [comment]
Now I understand
Thank you.
