### ISSUE TITLE
Question regarding multiple registrations in a vault

### ISSUE THREAD

**Issue by rmbolger** [ebekker/ACMESharp#111]
Forgive me if creating an issue ticket isn't the right place for this type of question. I wasn't sure where else to ask.

I'm trying to figure out how multiple registrations work in a single vault. In the subsequent commands like `New-ACMEIdentifier`, there doesn't appear to be a way to specify which registration you want to use. Do all of them get used simultaneously or am I missing an argument somewhere?

**Comment by bseddon** [comment]
The command New-ACMEIdentifier is used to create an 'alias' on the Let's Encrypt servers for a domain for which you want to create a certificate.  Each domain for which you want to create a certificate (or to create one certificate with multiple domains) needs to have its own alias and be separately validated.  A copy of the information created on the LE servers is recorded in the vault.

You can have as many aliases for a single domain as you want. In fact you going to create a new alias every time you want to create a new certificate for a domain which you will have to do at least every 90 days.

**Comment by ebekker** [comment]
A single Vault is tied to one registration (i.e. a single target service provider, like the Let's Encrypt beta service, or the Let's Encrypt Staging service).  But you can create multiple Vaults and associate a *Vault Profile* with each one so you can reference it in subsequent calls.  Use the `-VaultProfile` parameter to specify a specific Vault other than the default which is available in all ACMESharp cmdlets.

You can use the cmdlet `Get-ACMEVaultProfile` to get details about the existing Vault Profiles including the default (implicit) ones.  And you can use `Set-ACMEVaultProfile` to define a new profile and then initialize a Vault with that profile.
