### ISSUE TITLE
Get-ACMEIdentifier throwing NullReferenceException when called with no arguments and no identifiers exist in the vault

### ISSUE THREAD

**Issue by rmbolger** [ebekker/ACMESharp#113]
This may or may not be related to #112.

In a freshly created vault with at least one registration defined but no identifiers defined yet, I would expect that calling Get-ACMEIdentifier with no arguments would just return a null object or empty set. But it currently throws a NullReferenceException like this:

```
PS > Get-ACMEIdentifier
Get-ACMEIdentifier : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ACMEIdentifier
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ACMEIdentifier], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,ACMESharp.POSH.GetIdentifier
```

This makes it harder to filter or iterate over results because you need catch the potential exception first. If it returned a null object or an empty set, the iterating would simply end doing no work and filtering would simply return no results.

**Comment by rmbolger** [comment]
I just realized that the Get-ACMEIdentifier code has changed in the master branch since the 0.8.1 release version I was testing against.  Specifically, PR #82 changes things so that an ItemNotFoundException is thrown instead when there are no Identifiers in the vault yet.

I would argue that this logic could be further improved based on the semantic difference between calling Get-ACMEIdentifier with no IdentityRef (*Give me all Identifiers*) and with an IdentityRef (*Give me this specific Identifier*).

I propose the following pseudo-code:

* If no IdentityRef specified
 * If no Identities in vault, return null
 * Else, return all Identities
* Else
 * If no Identities in vault or the specified ID is missing. throw ItemNotFoundException
 * Else, return the specified Identity

I've already started working on the implementation for this if there is agreement. Just let me know and I'll submit the PR.

**Comment by bseddon** [comment]
I hope @ebekker looks favourably upon your suggested update.

**Comment by ebekker** [comment]
Go ahead and submit a PR, I'll be happy to accept.

**Comment by rmbolger** [comment]
Done

**Comment by ebekker** [comment]
I've merged the change.
