### ISSUE TITLE
Allow aliases to be reassigned (or removed)

### ISSUE THREAD

**Issue by ebekker** [ebekker/ACMESharp#118]
Aliases allow you to associate a human-friendly identifier with different entities in the ACMESharp Vault so that they can be referenced more easily and more logically.  Currently, once an alias is assigned to a given entity type (e.g. VaultProfile, Identifier, Certificate, etc.) it is permanently tied to that entity instance.

However there is no reason why the alias could not be unassigned or reassigned to a different instance in order to update the _logical notion_ of what that instance represents.  This ticket is to allow removing an alias or reassigning it to a different instance.

The only constraint that must be enforced is that an alias must be unique within a given entity type.

This request is inspired by @mikeobrien in [this comment](https://github.com/ebekker/ACMESharp/issues/88#issuecomment-199006360).

**Comment by centur** [comment]
Is there any chance to see progress on this ?

**Comment by ebekker** [comment]
The next release will include the ability to move or remove an alias on certain entities in the PowerShell module.

Specifically, with Identifiers and Certificates, you can rename or remove the alias by passing in the `-NewAlias` flag to the `Update-ACMEIdentifier` and `Update-ACMECertificate` cmdlets.  If you want to *move* and alias around say from an old, expired certificate to a newer cert that's taking it's place, remove it from the old (i.e. rename the alias to an empty string) and rename the new one or simply use the same alias when you ceate a new cert after removing it from the old.

**Comment by ebekker** [comment]
Similarly, Profiles, which are a special case of aliases under the hood, can now be renamed.  Simply pass in the `-Rename` parameter to either of these:
* `Set-ACMEChallengeHandlerProfile`
* `Set-ACMEInstallerProfile` - Installers are a new concept that will be included in the next release

Vault Profiles cannot be renamed as yet, since they use a fundamentally different mechanisum under the hood.  If this is something that's desired, please open/vote up in a separate ticket.

**Comment by ThomasCr** [comment]
Can you pls provide a PS example to delete a identifier, because I cant figure it out myself.

**Comment by ebekker** [comment]
That's correct -- it's in the source repo but it's not in any of the releases yet.  It will be included in 0.8.2 release.
