### ISSUE TITLE
Change Manual Challenge Handler output to object

### ISSUE THREAD

**Issue by garrathleeds** [ebekker/ACMESharp#125]
In PowerShell the Manual Challenge Handler is outputted to the host, which makes it difficult to capture in a variable. Is it possible for this to be changed to an object or at least to a stream that is easily captured?

Thanks

**Comment by bseddon** [comment]
Why do you need to capture it?  Once you have submitted a challenge you can retrieve the status at any time by issuing a Get-ACMEIdentifier -youralias command.  The challenges can be viewed using something like:

(Get-ACMEIdentifier -youralias).Challenges

There are examples in other posts showing how filter this collection to, for example, display valid challenges or the http challenge.

You will likely have to use the Update-Identifier -youralias command after the submit command to make sure ACMESharp has retrieved the latest state from the LE servers.

**Comment by ebekker** [comment]
I think this is doable, so I'll research it when I get around to cleaning up the output from some of the other cmdlets.  I agree this is more inline with the spirit of POSH, and I think some formatting rules could be used to still make the output of the object pretty-print by default.

**Comment by garrathleeds** [comment]
It information required isn't outputted by the Get-ACMEIdentifier, it is the Manual Challenge Handler information I am after. The reason to catch it is so we can automate the process. Some setups can only be done manually, but the tasks from then on can be automated (placing the file on the web server/s, adding the content...).

Thanks

**Comment by bseddon** [comment]
The manual challenge information is there.  A while ago I created a PowerShell script to automate the process because I don't want to remember all the steps.  You can find it in post 76 [here](https://github.com/ebekker/ACMESharp/issues/76#issuecomment-174705344).

If you review the script you can see how the information required to complete the manual HTTP challenge is accessed, a resource of the correct name is created which includes the necessary challenge token.

If nothing else it will allow you to explain how I've missed the point.

**Comment by garrathleeds** [comment]
Damn, not sure how I missed that - I guess I didn't go that far into the object. Exactly what I need. Thanks for your help!

**Comment by ebekker** [comment]
Manual Challenge Handler has been updated with a new `OutputJson` parameter that spits out the handling details as JSON blob for easier parsing.  See #270 for details.

It's not a PS object, but you can convert it easily to one by piping to `ConvertFrom-JSON`.  The ticket has a sample that shows just that.
