### ISSUE TITLE
This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

### ISSUE THREAD

**Issue by octogondude** [ebekker/ACMESharp#126]
I've opened this issue over at letsencrypt-win-simple, but was told that the error comes from the ACMESharp library and to open an issue here. Anyways, here it goes:

> Trying to use letsencrypt-win-simple on our security hardened Windows Server 2012 R2 to obtain a certificate for one of our IIS Site bindings i get the following error:
> 
>     System.Reflection.TargetInvocationException: Exception has been thrown by the ta
>     rget of an invocation. ---> System.InvalidOperationException: This implementatio
>     n is not part of the Windows Platform FIPS validated cryptographic algorithms.
>     at System.Security.Cryptography.SHA256Managed..ctor()
>     --- End of inner exception stack trace ---
>     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
>     Signature sig, Boolean constructor)
>     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, B
>     inder binder, Object[] parameters, CultureInfo culture)
>     at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Obje
>     ct[] args)
>     at System.Security.Cryptography.SHA256.Create()
>     at ACMESharp.JOSE.JwsHelper.ComputeKeyAuthorization(ISigner signer, String to
>     ken)
>     at ACMESharp.ACME.Providers.HttpChallengeDecoder.Decode(IdentifierPart ip, Ch
>     allengePart cp, ISigner signer)
>     at ACMESharp.AcmeClient.DecodeChallenge(AuthorizationState authzState, String
>     challengeType)
>     at LetsEncrypt.ACME.Simple.Program.Authorize(Target target)
>     at LetsEncrypt.ACME.Simple.Program.Auto(Target binding)
>     at LetsEncrypt.ACME.Simple.Plugin.Auto(Target target)
>     at LetsEncrypt.ACME.Simple.Program.Main(String[] args)
>     Press enter to continue.

**Comment by bseddon** [comment]
I guess you have two solutions.  One will be to compile ACMESharp and change the call to SHA256.Create() to SHA256Cng.Create() on line 173 of file '.\ACMESharp\ACMESharp\JOSE\JwsHelper.cs' so the hash algorithm used is the FIPS compliant one.

The other will be to use ACMESharp on a different machine that does not use the FIPS registry setting and either use the DNS challenge or the HTTP challenge and add the challenge token to the web site on the web server manually.

**Comment by ebekker** [comment]
I'll create an enhancement request to be able to support this better natively in the future, but if you really need it now, I agree with @bseddon, those are you best immediate options.

**Comment by ebekker** [comment]
@octogondude, thanks to @bseddon for digging a little deeper into the situation in #128, you may have an alternative for your immediate case.  He referenced [this StackOverflow](http://stackoverflow.com/questions/20142846/why-do-all-the-variants-of-sha256-appear-as-sha256managed) article which reminded me that I'm just invoking the *default* implementation of the SHA2 hashing algorithm and by default this will make use of the managed implementation, but you as the user can override what is the default implementation either a the machine level, via `machine.config` or even at the application level via `app.config`.

In the case of PowerShell, you can either modify the .config file for the whole of the PowerShell system, which may not be a bad idea in your case anyway, since it would *harden the default* used in other cases of PowerShell for your secure environment, or there appears to be way to do it on a script-by-script basis, based on [this](http://stackoverflow.com/questions/17960/powershell-app-config).

Hopefully this addresses your immediate need.

**Comment by bseddon** [comment]
@ebekker read the StackOverflow more carefully than me.  On re-reading I can see it is possible to change the default algorithm used dynamically. This command will change the default SHA256 algorithm used from SHA256 to SHA256Cng:

```
[System.Security.Cryptography.CryptoConfig]::AddAlgorithm([System.Security.Cryptography.SHA256Cng], "System.Security.Cryptography.SHA256")
```

You can test this using the command:
```
[System.Security.Cryptography.SHA256]::Create().GetType().Name
```
When you should see the name is reported as SHA256Cng not SHA256 as it normally would.

These changes do appear to be ephemeral.  When the shell ends the next invocation of the shell does not have a changed configuration.

I've not tested to see if this configuration change is still in place when an ACMESharp command is run though I've reason to believe it will not be.

**Comment by ebekker** [comment]
Good deal, that's even better as you don't have to mess with .config files anywhere, just make the change in your POSH script or at the start of your session.

**Comment by octogondude** [comment]
Thank you very much for all of your input!

**Comment by flennic** [comment]
A nice workaround which worked for me and may help the people coming to this issue from lets-encrypt-simple:

If there is a .config file (mine was letsencrypt.exe.config) insert the following marked with stars:

```
<runtime>
    **<enforceFIPSPolicy enabled="false/">**
    ...
</runtime>
```

This disables the policy for this program only and you can delete the line after you're done. Hope that helps someone.

Cheers
flennic

**Comment by ebekker** [comment]
Thanks @flennic !

**Comment by blakeduffey** [comment]
Thanks so much!  I HAVE been accused of being 'too literal' :)
