### ISSUE TITLE
Writing private key to disk fails if file encryption not supported

### ISSUE THREAD

**Issue by jduncanator** [ebekker/ACMESharp#129]
When using `LocalDiskVault.CreateAsset` to create sensitive assets it assumes that every user has Encrypted file support, which isn't always the case.

On [this line](https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.Vault/Providers/LocalDiskVaultProvider.cs#L278-L279), ACMESharp attempts to create a file stream with the Encrypted flag set. However on machines that are not using NTFS (eg. mono on Linux/MacOSX), or for some reason do not support Encrypted files, the call to `File.Create` will throw an UnauthorizedAccessException which can be somewhat confusing to users. See the exception information on [MSDN](https://msdn.microsoft.com/en-us/library/ms143360.aspx), and notice the third clause of the UnauthorizedAccessException, for more information.

As a solution, I propose encryption of the private key be implemented via one of two industry standard ways of encrypting private keys, both of which are compatible with nginx and Apache (the only time you'd ever use the PEM file by itself. IIS uses PFX files and these already have encryption support on export in ACMESharp).

The first is implementing PKCS#8 Section 7, the encryption of private key data stored in a PEM container. Appropriate specs are in [RFC5208](https://tools.ietf.org/html/rfc5208#section-6), and source code for it can be found [here](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/openssl/Pkcs8Generator.cs) in BouncyCastle.

The second is implementing the non-standard PKCS#1 style encryption that OpenSSL uses by default for encrypting RSA Private Keys. Relevant information on this can be found in this [RFC](https://tools.ietf.org/html/rfc1421#section-4.6). Source in BouncyCastle can be found [here](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/openssl/PEMUtilities.cs).

Both of these formats are fully supported in nginx and Apache and provide more security than using the built-in file encryption support Windows provides. They are also platform agnostic and would work anywhere .NET runs rather than relying on a feature that is only available under Windows on NTFS.

**Comment by ebekker** [comment]
That's a good catch, I will need to think about what alternatives I have for this use case (filesystem without encryption support).

The solution you proposed is great for the *exported* artifacts, for example when a user is exporting the different components like private key or CSR or certificate.  In that case, they can provide necessary parameters to secure the generated output or alter what format it's stored in.

But the situation here is that this is a call to secure an asset stored *internally* in the Vault so it's trying to secure the necessary components transparently.  What I'll pby end up doing is testing to see if the target file system supports encryption when the Vault is first initialized, and if not fail immediately at that time unless the user provides some override option during initialization.

**Comment by ebekker** [comment]
For your immediate situation, do you have access to any NTFS file system on the target system you're running ACMESharp on?  It doesn't have to be the default system drive (usually C:), as long as it's reachable by path.  If so, then I suggest you create a VaultProfile giving the NTFS drive as your target path, and then reference the profile in all subsequent operations.

**Comment by jduncanator** [comment]
Interestingly, I actually opened this ticket because I am using an NTFS filesystem and Encrypted files do not work (for some unknown reason, I didn't investigate this).

I've managed to work around this for now by compiling a custom version that disables encrypted files, but would like a more maintainable solution going forward.

**Comment by ebekker** [comment]
The PEM files are only one type of artifact that are stored securely in the Vault.  Other artifacts include DER-encoded files and JWS encryption keys in a JSON format.  The Vault API is intentionally structured to generically support storage of any type of asset, either those that are known now, or that may come up in the future, where as the PKCS encryption types you're referring to are specific to encrypting PEM containers.

**Comment by ebekker** [comment]
Now, the Vault API is intentionally provider-oriented, meaning you could swap out any storage provider you want as long as it conforms to the [interface specification](https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.Vault/IVault.cs).  This was primarily done in order to support storage systems other than file-based ones (e.g. RDBMS or NoSQL storage services), but you can easily drop in your own variation of a file system provider that does its own thing when it comes to *sensitive* files.

**Comment by jduncanator** [comment]
Interesting. I think for now we should concentrate on at least handling this edge case. Would love to be able to use the latest version of ACMESharp without having to recompile every time.

**Comment by jduncanator** [comment]
Where are we at with this? An alternate option would be to use [ProtectedData](https://msdn.microsoft.com/en-us/library/system.security.cryptography.protecteddata.aspx). This is essentially the same as using file system encryption (the key is based on the current users credentials), however it is handled by the software, rather than the file system. The scope could even be tweaked to allow the current machine access to the files.

This would satisfy all the requirements you outlined above, as well as support everything back to Windows 2000.

**Comment by ebekker** [comment]
This issue and the solution are more fully documented [here](https://pkisharp.github.io/ACMESharp-docs/Local-Vault-EFS).
