### ISSUE TITLE
SAN support?

### ISSUE THREAD

**Issue by cbergcreate** [ebekker/ACMESharp#13]
The linux client supports multiple host names (SAN) - is this possible with this client?

**Comment by ebekker** [comment]
It should be, I need to take a look at the right set of options that need to be passed into the OpenSSL CSR generation.

**Comment by matbech** [comment]
To add extensions to a certificate take a look at this sample:
https://github.com/openssl-net/openssl-net/blob/899a40d7f0e98969f36909c852ca59f4e48b35bc/test/TestX509Certificate.cs#L371

The extension name your are looking for is:
"subjectAltName"

which gets you to:
new X509V3ExtensionValue("subjectAltName", false, "DNS:server1.example.com")

**Comment by ebekker** [comment]
@matbech, thanks for the find.  I'll incorporate this into the refactor of the [CSR/cert management changes](../16)  I'm working on right now.  At least for the OpenSSL CLI provider I'll be adding, I'll be able to incorporate the SAN feature.

**Comment by Reltik** [comment]
@ebekker the link gives 404

**Comment by DanielBrownAU** [comment]
+1 for SAN support

**Comment by jplandry908** [comment]
Agreed. +1 for SAN support. Also, we appreciate all of your hard work ebekker!

**Comment by ezeeetm** [comment]
@ebekker can you confirm that multi domain SAN certs are currently still unsupported at this time?

Also, do we need to build this project first to get the main .psm1 for "Import-Module ACMEPowerShell"?  I see the psd1 in \ACMESharp-master\ACMESharp\ACMESharp.POSH, but nothing I drop into any of my standard ps modules paths are working.  I get no module found on each attempt of Import-Module.

**Comment by skipperen** [comment]
+1 for SAN support

**Comment by barsk** [comment]
+1 for SAN support too. This is needed for the MDaemon mail server to support multiple domains.

**Comment by leonletto** [comment]
Another +1 for SAN :)   Awesome work!

**Comment by Hypopheralcus** [comment]
+1 for SAN support

**Comment by GioviQ** [comment]
+1 for SAN support

**Comment by gijswijs** [comment]
+1 for SAN support. Awesome work by the way. You guys save me laods of time and money. I'm really happy with this!

**Comment by ruohki** [comment]
id love san support

**Comment by japerlman** [comment]
Waiting on SAN support for a project, would it help to get a bounty on this or should I just pay for some certs for now?

Thanks for the great project, 
Jason.

**Comment by SpikeTheMaster** [comment]
+1 for SAN support

**Comment by formula349** [comment]
I was able to get SAN certificates working by generating the RSA keys and the CSR with Bouncy Castle and using those instead. Works great!

**Comment by ebekker** [comment]
@formula349, that's great news -- did you use the C# implementation of Bouncy Castle?  Via API code or via command-line?

**Comment by formula349** [comment]
Yes, I'm using the NuGet package Portable.BouncyCastle v1.8.1

Took some time to figure it out, as I couldn't find any real documentation on the BouncyCastle API. This link is what finally did the trick, though I had to use the string version of the X509Name constructor.

https://gist.github.com/Venomed/5337717aadfb61b09e58

**Comment by mInternauta** [comment]
@formula349 @ebekker and how after all was the support SAN? Could share the solution?

**Comment by ebekker** [comment]
The ACMESharp PS module allows you to supply your own private key and CSR PEM files instead of generating them (take a look at the New-ACMECertificate options).  So @formula349  created the private key and CSRs separately using BouncyCastle and then supplied those as parameters.

The SAN part of the request is actually a CSR extension field that lists the alternate names, so you have to add that to the CSR.  And then submit that to the ACME server.

**Comment by mInternauta** [comment]
@ebekker  I realized and I am already implementing the construction of RSA Keys and CSR by BouncyCastle. I was just trying to find out if the ACMESharp already implement a native form.

 Thanks

**Comment by brettyj** [comment]
+1 Could really do with this! I have quite a few subdomains and I keep hitting the rate limits

**Comment by brettyj** [comment]
I'm happy to potentially try the @formula349 method if someone could write up exactly what to do - while I am a C# dev, I'm new to the inner workings of SSL

**Comment by Tondas** [comment]
+1 for SAN, However ACMESharp is really useful for me. Thank you Eugene.

**Comment by ebekker** [comment]
I've updated the [Quick Start guide](https://github.com/ebekker/ACMESharp/wiki/Quick-Start) with directions on how to include SAN entries.
