### ISSUE TITLE
Unable to submit certificate

### ISSUE THREAD

**Issue by KirillSemenoff** [ebekker/ACMESharp#130]
Hey there

I do realize there had been much similar questions, however I was not able to find solution

So, I successfully passed the challenge and generated the certificate, which showed me smth like this

Id                  : d66e9537-a96d-465e-8385-679b9c0287fb
Alias               : cert5
Label               : 
Memo                : 
IdentifierRef       : e8ea15cd-5344-42b1-84d2-54048d3ddfec
KeyPemFile          : 
CsrPemFile          : 
GenerateDetailsFile : d66e9537-a96d-465e-8385-679b9c0287fb-gen.json
CertificateRequest  : 
CrtPemFile          : 
CrtDerFile          : 
IssuerSerialNumber  : 
SerialNumber        : 
Thumbprint          : 
Signature           : 
SignatureAlgorithm  : 

When I try to submit it, I get the error:
 Submit-ACMECertificate : Unexpected error
At line:1 char:1
+ Submit-ACMECertificate cert5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMECertificate], AcmeWebException
    + FullyQualifiedErrorId : ACMESharp.AcmeClient+AcmeWebException,ACMESharp.POSH.SubmitCertificate

The Update is not working since the submit does not.

When I try to submit the same cert once again, it says-Submit-ACMECertificate : asset file already exists

Please help

Thanks in advance

**Comment by bseddon** [comment]
It's hard to know how to respond because it's not clear what commands you have run.  Can you post a complete transcript so it's possible to follow along?

**Comment by KirillSemenoff** [comment]
Hey there,

It seems that the problem was due to Azure. I was generating the cert for the machine on Azure, and certs for Azure domains had excceded some kind of limit. It was impossible to understand it from the acme error output, however the problem was in it.

So let's mark it as resolved :)
