### ISSUE TITLE
LocalDiskVaultProvider File encryption for sensitive information is not secure for certain Windows editions

### ISSUE THREAD

**Issue by naammeinkyahai** [ebekker/ACMESharp#134]
LocalDiskVaultProvider uses CreateFile with FileOptions.Encrypted attribute. .NET CreateFile method is implemented using the [Win API CreateFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858%28v=vs.85%29.aspx)
This is what that link has to say about FILE_ATTRIBUTE_ENCRYPTED

> This flag is not supported on Home, Home Premium, Starter, or ARM editions of Windows.

I will try to find a machine with Home edition to reaffirm but my guess is file is being stored in plain text.

Probably another mechanism such as DAPI, exposed via [ProtectedData](https://msdn.microsoft.com/en-us/library/system.security.cryptography.protecteddata%28v=vs.110%29.aspx) should be considered for storing data.

**Comment by ebekker** [comment]
That's a good catch.  The encrypted filed attribute is based on EFS, which you are correct, is not supported in Home and similar editions of Windows.  Ironically, EFS is itself built on top of DPAPI to secure the certificates that are in turn used to secure the files.

**Comment by ebekker** [comment]
If you do get an opportunity to test this out on Home edition, I would be curious to know if you encounter an exception as was described in #129, or if it just silently fails and reads/writes in clear text.

**Comment by naammeinkyahai** [comment]
#129 is different because it involves lack of the underlying API. In the scenario I described, it will read/write in cleartext.

I was debugging today on Windows 7 Enterprise. When I ran the code from VS 2015 (POSH launched in x86 debug), the key PEM file was correctly encrypted (looks green in explorer and has the encrypted attribute set in file properties). 

On the same machine, I had created other certs previously using ACMESharp 0.8.1 installed from Powershell gallery and those were cleartext. I was so surprised that I created two more certs, one from x86 powershell window and another from x64. Both of them created the Key PEM files in cleartext. 

Login from another Windows account on the same machine only prevented me from reading the one file created via debug session in VS. Others were accessible.

This is a bigger problem than the Home edition one described  above.

**Comment by ebekker** [comment]
Yes, the way the issues present may be different but the solution may be the same for both of them, i.e. alternative support from the OS or not even relying on the OS to secure some artifacts in the Vault.

**Comment by ericwj** [comment]
Please don't use OpenSSL - there are many advantages of using the OS encryption facilities, the most obvious one being that private keys won't have to go in plain disk files for many scenario's.

The first thing I wanted after requesting a certificate successfully was move the vault and have it work on another computer. Moving the folder broke AcmeSharp - I'm now puzzling over what Hashtable Set-AcmeVaultProfile requires in the parameters arguments. Off topic but consider adding dynamic parameters or at least a command that can create a suitable parameters object/hashtable.

Take a look at [Certificate-based encryption with Windows DPAPI-NG in .NET Core RC2](https://docs.asp.net/en/1.0.0-rc2/security/data-protection/implementation/key-encryption-at-rest.html#certificate-based-encryption-with-windows-dpapi-ng), since that is most likely what I want to use and DPAPI(-NG) supports a number of other methods that'll be suitable as defaults for local&domain user&system.

**Comment by webprofusion-chrisc** [comment]
Hi, I'm using Home edition to develop on and have encountered the issue that the encryption flag causes failure with access denied. Modifying the asset file creation to not use the secure flag fixes this, suggest that this becomes an optional flag but the question is where in ACMESharp should configuration be set?
`
Exception thrown: 'System.Management.Automation.CmdletInvocationException' in System.Management.Automation.dll
System.Management.Automation.CmdletInvocationException: Access to the path 'C:\ProgramData\ACMESharp\sysVault\45-KEYPM\98e48b19-5f5c-46c0-bf5d-e1f5b4d154da-key.pem' is denied. ---> System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\ACMESharp\sysVault\45-KEYPM\98e48b19-5f5c-46c0-bf5d-e1f5b4d154da-key.pem' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.Create(String path, Int32 bufferSize, FileOptions options)
   at ACMESharp.Vault.Providers.LocalDiskVault.CreateAsset(VaultAssetType type, String name, Boolean isSensitive, Boolean getOrCreate)
   at ACMESharp.POSH.SubmitCertificate.ProcessRecord()
`

**Comment by ebekker** [comment]
The "Secure Flag" is an implementation detail of the `LocalDiskVaultProvider` -- the default Vault provider that uses the local host's file system.  For Vault Assets that are flagged as *sensitive*, it uses a simple and naive approach by relying on the OS's Secure Flag.

It would be in this specific provider that I would add an option to skip using the Secure Flag.  As described above, I would also add an alternative method to secure sensitive artifacts, for example allowing the user to specify an optional key or password that would be used to use symmetric encryption to secure the sensitive artifacts in the application tier as opposed to relying on the OS.

**Comment by ebekker** [comment]
This issue and the solution are more fully documented [here](https://pkisharp.github.io/ACMESharp-docs/Local-Vault-EFS).
