### ISSUE TITLE
"New-ACME ProviderConfig" : error = is not recognized as the name of a cmdlet  ,etc ...

### ISSUE THREAD

**Issue by acusig** [ebekker/ACMESharp#137]
Hello, as a first try to install Let's Encrypt trough ACMESharp v0.8.1.0, I get this error from powershell window when I try to execute the New-ACME ProviderConfig step. Everything was fine until that.
I'm under Win 2008 r2 sp1, Powershell v4.0
Any help will be appreciated, have a nice day !

Pierre

![acmeproviderconfig](https://cloud.githubusercontent.com/assets/3855578/15520888/ce1ed13e-2208-11e6-8f92-0d9d8b815855.png)

**Comment by bseddon** [comment]
What makes you think such a command exists?  I've just looked through the code and there is no command like this which would explain your observation.  Where did you get the instruction to use this command?  Have you followed the commands in the [quick start](https://github.com/ebekker/ACMESharp/wiki/Quick-Start) guide?

**Comment by acusig** [comment]
Hi bseddon, you're right, I mismatched the versions and the command I was looking for has been deprecated. Thanks for pointing out my mistake !
