### ISSUE TITLE
How to view challenge details?

### ISSUE THREAD

**Issue by martinrotter** [ebekker/ACMESharp#142]
Hello, I ran "Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler manual" and info about where to place given "challenged" file on the web server showed up. Unforunatuly I accidentally closed powershell window and any subsequent calls to "Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler manual" do not show needed info again.

What should I do?

**Comment by bseddon** [comment]
You can find all information about a challenge in the identifier object.  For example:

```
(Get-ACMEIdentifier <your identifier>).Challenges
```

This lists all challenges (there will always be 3).  To select the http-01 use this command:

```
(Get-ACMEIdentifier <your identifier>).Challenges | Where-Object { $_.Type -eq 'http-01' }
```

The information you require is in the 'Challenge' property.  Here's how you will access name of the expected file name and the corresponding token to used as the file's content:

```
((Get-ACMEIdentifier wordpress.wproute-2016-05-22-2).Challenges | Where-Object { $_.Type -eq 'http-01' })[0].Challenge
```

**Comment by martinrotter** [comment]
Thanks for hints, it was helpful. :)

**Comment by ebekker** [comment]
You can also force the `Complete-ACMEChallenge` cmdlet to repeat the same set of instructions by giving it the `-Repeate` and/or `-Regenerate` flags.  When using the `Manual` challenge handler, it simply reprints the same set of instructions over and over.
