### ISSUE TITLE
Full Chain download?

### ISSUE THREAD

**Issue by xied75** [ebekker/ACMESharp#144]
Hi there,

Some times we need the full chain crt pem file, i.e just a concat of the cert with the intermediate cert in one single text file, is that possible to have a command for this?

Best,

Edit: one situation would be using curl in Linux, if the pem we configured on Nginx is not full chain, it will stop working. The full chain can be made by joining the server certificate with Issuer Certificate, and the server cert should be at top.

**Comment by ypid** [comment]
Related to: https://github.com/diafygi/acme-tiny/issues/77

**Comment by ThomasCr** [comment]
a current workaround is this:

```
$CertOutPath = "C:\Some\Folder\you\like"

Get-ACMECertificate cert1 -ExportKeyPEM "$CertOutPath\cert1.key.pem"
Get-ACMECertificate cert1 -ExportCertificatePEM "$CertOutPath\cert1.crt.pem"
Get-ACMECertificate cert1 -ExportIssuerPEM "$CertOutPath\cert1.issuer.pem"

Set-Content "$CertoutPath\cert1-all.pem" -value (Get-Content "$CertOutPath\cert1.*.pem" )
```

**Comment by ebekker** [comment]
I would recommend going with @ThomasCr 's approach -- that's the power of using PowerShell.

Since there's been no other activity on this ticket, I'm going to close for now.
