### ISSUE TITLE
https only Complete-ACMEChallenge

### ISSUE THREAD

**Issue by ctaggart** [ebekker/ACMESharp#145]
Is there a way to complete the change using a `https` uri instead of a `http` uri? Our app enforces `https`, but with a self signed certificate to begin with. I want to replace it with one from Let's Encrypt, but I don't know how to make the challenge be over `https`.

**Comment by bseddon** [comment]
No, this is a Let's Encrypt constraint.  Let's Encrypt servers will only query http.  If you are forced to use https then you will need to use the DNS authentication method.

**Comment by ctaggart** [comment]
Thanks. I'll use DNS.
