### ISSUE TITLE
Does SAN work?

### ISSUE THREAD

**Issue by benlumia007** [ebekker/ACMESharp#149]
I still don't understand how the SAN work. so im assuming this isn't an issue. i follow the steps from 1 to 6 and when it comes 7.. im confused. 

Anyone.

**Comment by bseddon** [comment]
Can you explain your confusion?  The process is that you will loop around the New-ACMEIdentifier/Complete-ACMEChallenge/Submit-ACMEChallenge commands for each domain you want to appear in the certificate then create the certificate using the references used when you issue each  New-ACMEIdentifier command.

If you will only use the http verification method I created a script to handle all these steps.  You can find it attached to this issue: https://github.com/ebekker/ACMESharp/issues/76#issuecomment-174705344

**Comment by benlumia007** [comment]
actually i got the three i wanted and its all valid, but when i used

New-ACMECertificate www.ichirolu.com -Generate -AlternativeIdentifierRefs ([array]$('dns2-072016','dns3-072016')) -Alias multiNameCert

it says that the given key was not present in the dictionary

**Comment by benlumia007** [comment]
New-ACMECertificate dns-072016 -Generate -AlternativeIdentifierRefs ([array]$('dns2-072016','dns3-072016')) -Alias multiNameCert

it says that the given key was not present in the dictionary.

**Comment by benlumia007** [comment]
sorry, it seems like i got it :) fiNALLY

**Comment by bseddon** [comment]
OK, good to learn you are on your way.  I think based on your post in 104 you had the wrong alias name
 as the first parameter.

**Comment by benlumia007** [comment]
Excellent! some of your posts helped a lot actually. i was trying to figure out why the alternativeidentifierref did't work so i look through that it needed to be an array :) so cool 

thanks

**Comment by benlumia007** [comment]
Closing ticket!
