### ISSUE TITLE
Private Keys in plaintext in SysVault

### ISSUE THREAD

**Issue by gargricha01** [ebekker/ACMESharp#153]
Hello,
I installed ACMESharp client and requested certificate from LE. But I can see the private keys in SysVault along with the relevant certificates in PEM and DER formats. Just wanted to ask - 
1. If there are any plans to store the private keys in a secured manner (instead of just plaintext)
2. Can HSM be leveraged for securing the private key?
I look forward for your support. Thanks.
Regards,
Richa

**Comment by ebekker** [comment]
When the *sensitive* assets are saved to the Vault, the files are written with the `Encrypted` attribute set, which normally means the files are saved using EFS encryption.  However, if the target filesystem does not support the `Encrypted` flag, then the files will remain in the clear.

If you are looking at the files and they appear to be clear text, you can see if they are in fact encrypted on disk by inspecting the file's **Properties > `Advanced` > `Encrypt contents to secure data`** flag.

**Comment by ebekker** [comment]
I may add support for optional encryption of the sensitive assets with an encryption key or password as part of a fix for #134, but nothing is planned at this time.

At this time there are no plans to integrate HSM support explicitly into ACMESharp, but contributions are welcome!
