### ISSUE TITLE
Certificate Duplication issue

### ISSUE THREAD

**Issue by gargricha01** [ebekker/ACMESharp#154]
Hi,
I had requested two certificates from LE for the same domain in a span of 2 weeks. Now, both the certificates are valid, though I have done the binding with the most recent certificate. Is there any way, where certificate duplication issue can be addressed - for e.g., LE client can check for an existing certificate before sending a new cert request?
Thanks.

**Comment by bseddon** [comment]
Certificates are tied to aliases (IdentifierRef values).  Only one certificate will be generated per alias.  If you use two different aliases for the same domain you will have two certificates - and both will be valid.  You can use PowerShell to query the Windows certificate store for existing certificates and take action based on the result.
