### ISSUE TITLE
Certificate Revocation

### ISSUE THREAD

**Issue by gargricha01** [ebekker/ACMESharp#155]
Hello,
I understood that currently, the feature to request for the revocation from PowerShell is not available. But is there any other way, where the certificate revocation can be done? Like team managing the CA server can take the request (over email or forum) and revoke the certificate?
Also, does it mean that no CRLs are published so far for the certs issued to Windows clients?

**Comment by ebekker** [comment]
Yes, LE uses CRLs, see [here](https://letsencrypt.status.io/) and [here](https://community.letsencrypt.org/t/pros-and-cons-of-90-day-certificate-lifetimes/4621/34).

In general LE does not support any manual method of cert management, that is the whole idea of LE service and ACME protocol -- it's all automated which makes it feasible from a cost perspective.

Your other alternative is to use one of the other clients on another platform, such as certbot on Linux.
