### ISSUE TITLE
Get-Certificate cmdlet already exists during install

### ISSUE THREAD

**Issue by mbreaton** [ebekker/ACMESharp#159]
Trying to run the following shell commands

**Install-Module -Name ACMESharp 
Install-Module -Name ACMESharp -Scope CurrentUser** 

on a Windows 10 1607 install and getting following error:

**PackageManagement\Install-Package : A command with name 'Get-Certificate' is already available on this system. This
module 'ACMESharp' may override the existing commands. If you still want to install this module 'ACMESharp', use
-AllowClobber parameter.**

anyone else seeing this? any workarounds without clobbering the one already installed? I verified ACMESharp is not already installed.

Thanks,

Mike

**Comment by bseddon** [comment]
The ACMESharp command is Get-ACMECertificate.  You can see in the ACMESharp.psd1 module a default command prefix of 'ACME' applied to all commands.  Maybe you could try running the command using 

Install-Module -Name ACMESharp -Prefix ACME 

This would be to make sure the prefix used really is 'ACME'.

**Comment by mbreaton** [comment]
Thanks for the response.

**-Prefix** is not an option on this version of PS (5.1)

I'm thinking the install is somehow checking for the non-prefixed version, even though it will install with the prefix.

**Comment by bseddon** [comment]
Was it dropped from 5.1?  The argument has been part of PS since version 3.0 and is shown in the [version 5.0 documentation](https://technet.microsoft.com/en-us/library/hh849725.aspx).

Get-Certificate is a valid command in all versions of PS so it seems this would be a command we'd all see clobbered if it were a general problem.

There was a news story last week that [Microsoft 'broke' Powershell in Windows 10](http://www.theregister.co.uk/2016/08/25/microsoft_breaks_powershell_with_borked_update_wont_fix_it_for_a_week/) with the last update.  Maybe this is contribution to your issue?  I believe this is scheduled to be addressed in the next update.

**Comment by mbreaton** [comment]
That's part of the **Import-Module** used to load the module into the current session. I get the error during the **Install-Module** which essentially downloads the bit

**Comment by mbreaton** [comment]
I tried it with the **-AllowClobber** option and the install looked to be successful. The original **Get-Certificate** still work and **Get-ACMECertificate** appears to run as well. My guess is the installer is looking for the non-aliased name even though it will use a prefix.

**Comment by rmc47** [comment]
This is also true on Windows Server 2016 (RTM, as seen on Amazon AMI Windows_Server-2016-English-Full-Base-2016.10.18 / ami-7ac78809)

AllowClobber works, but doesn't feel like the right answer?

**Comment by ebekker** [comment]
For some reason the "clobber checking" that's in the Install-Module or Import-Module doesn't look to see if there is a `DefaultCommandPrefix` in the module manifest, which ACMESharp does have (`ACME`) -- with that prefix (or even one that you can specify when you do the import) there is no clobbering.

I would venture to say that this is a bug or oversight on the part of these cmdlets.

**Comment by ThomasCr** [comment]
any update? problem still exists

**Comment by ebekker** [comment]
Apparently a [known problem](https://github.com/PowerShell/PowerShellGet/issues/45) with PowerShellGet.

**Comment by ebekker** [comment]
See [this article](https://pkisharp.github.io/ACMESharp-docs/Why-AllowClobber) for details about this issue.
