### ISSUE TITLE
3CX uses AMCESharp

### ISSUE THREAD

**Issue by bseddon** [ebekker/ACMESharp#166]
@ebekker Maybe you know this.  I installed the [3CX](3cx.com) last week which is a VoIP PBX for Windows.  During the install process it offers to generate an SSL certificate.  After installation, I wanted to change the certificate.  Hunting around the product files looking for information about how to make the change I discovered that it uses ACMESharp.  Bingo!  I knew what I had to do.  Nice to see it being used in a commercial product.

**Comment by ebekker** [comment]
Thanks Bill, I was not aware of this, yes, this is cool.

Are they also using your script to automate renewals and installation into IIS?
