### ISSUE TITLE
Specify optional attributes 

### ISSUE THREAD

**Issue by a-yakovlev** [ebekker/ACMESharp#169]
Hi! How specify a friendly name to certificate (and some optional attributes, like country, city etc).
In IIS cert looks like this
![default](https://cloud.githubusercontent.com/assets/22613910/19073781/7958657a-8a45-11e6-9d33-ba1ed534231b.png)

**Comment by bseddon** [comment]
I think you are supposed to be able to create a hashtable of the fields you want to add and pass the hashtable as the csrDetails argument value.

$crsDetauls = @{}
csrDetails['Country'] = 'US'

New-ACMECertificate $submitalias -Generate -Alias $certalias -CsrDetails $csrDetails

**Comment by a-yakovlev** [comment]
Thank you! Also i found a gui tool to set display name. https://www.digicert.com/util/

**Comment by bseddon** [comment]
I missed your question about the friendly name.  You can set the friendly name using PowerShell as part of the script you use to create your certificate.  Here's an example command:

(Get-Item "Cert:$certpath\$thumbprint").FriendlyName = "My certificate friendly name"

$certpath is folder the folder in the certificate you have selected to store your certificate
$thumbprint is the unique value of the certificate.

You can also set the friendly name using the certificate manager that comes with every edition of Windows.
