### ISSUE TITLE
Get dns-01 challenge infos

### ISSUE THREAD

**Issue by XSBen** [ebekker/ACMESharp#174]
Hi,

How can i get informations about dns-01 manual challenge in variable?

```
$challenge = Complete-ACMEChallenge $id -ChallengeType dns-01 -Handler manual

IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : s-exch2016-01.baclesse.fr
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/lyTCIBOePYOf4Q97qtYJEQGDQEuSLXutRlb****
Status         : pending
Expires        : 31/10/2016 08:43:14
Challenges     : {, , }
Combinations   : {1, 0, 2}

== Manual Challenge Handler - DNS ==
  * Handle Time:      [24/10/2016 10:43:16]
  * Challenge Token:  [9zTzEiyidqJ_q1t8FzYPvZ7hds9MgB3_gxZdfE****]
To complete this Challenge please create a new Resource
Record (RR) with the following characteristics:
  * RR Type:  [TXT]
  * RR Name:  [_acme-challenge.s-***.fr]
  * RR Value: [6M3IBmLvSo6jPIrZ5AHMHX2mrgwN2EU****]
```

But in $challenge I don't have _RR Type_, _RR Name_ and _RR Value_:

```
PS C:\Users\administrateur.BACLESSE> $challenge

IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : s-exch2016-01.baclesse.fr
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/lyTCIBOePYOf4Q97qtYJEQGDQEuSLXutRlb_7****
Status         : pending
Expires        : 31/10/2016 08:43:14
Challenges     : {manual, , }
Combinations   : {1, 0, 2}
```

**Comment by bseddon** [comment]
Run a command like:

((Get-ACMEIdentifier <your alias>).Challenges | Where-Object { $_.Type -eq 'dns-01' }).ChallengePart

You will get the information you need to complete the DNS record

**Comment by animetauren** [comment]
@XSBen I just figured this one out, this is how i got the information on the record name and value

This gives you the main information on both:
`($challenge.Challenges | Where-Object {$_.Type -eq "dns-01"}).Challenge`

The following will get you the Record Name:
`($challenge.Challenges | Where-Object {$_.Type -eq "dns-01"}).Challenge.RecordName`

The following will get you the Record Value:
`($challenge.Challenges | Where-Object {$_.Type -eq "dns-01"}).Challenge.RecordValue`

**Comment by ebekker** [comment]
Cool!

**Comment by XSBen** [comment]
Thank you @animetauren, it's perfect ! :)
