### ISSUE TITLE
Can not redirect ouput from Complete-ACMEChallenge

### ISSUE THREAD

**Issue by WallyRanson** [ebekker/ACMESharp#180]
Hi,
I am trying to do a powershell script, where I redirect the output to textfiles and then do some scripting on these, but whenever I try to do the line below then I only get the response equal to New-ACMEIdentifier.

Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual >> (c:\\ACME\\"+$Alias+".txt")

The ACMESharp command used before the Complete-ACMEChallenge is the New-ACMEIdentifier and maybe its just piping the same output once more.

How do I get the reply from the Complete-ACMEChallenge outputted to a file?

- Wally

PS: Tried with the CommonParameter -OutVariable, but with same result.

**Comment by bseddon** [comment]
Your command is asking you to set the same status on the same ACMESharp identifier object every time so you will get the same response.  It is like issuing the following command (after the New-ACMEIdentifier command has been used):

Get-ACMEIdentifier $alias

Why are you wanting to process the output in a text file?  If you issue a command like:

$myResult = Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual

$myResult becomes an object representing the completion result.  You can then query the output as much as you want and output the content to a file if you really want.

By using the stream redirector (>>) you are only outputting the content displayed in the PS console.  There is much more information in the ACME objects that will not be output using this technique.

**Comment by WallyRanson** [comment]
My ACMESharp command is correct and I get the right output in the PS console when I run it, but I can not get the text into a file.
The object you are making just returns exactly the same as I can get redirected into a file with my method, IE IdentifierPart, IdentifierType, Identifier, Uri, Status, Expires, Challenges and Combinations.
These all look like the NEW-ACMEIdentifier output earlier in the proces.

What I need to get redirected to the file is the info for the manual challenge handler, IE Handle Time, Challenge Token, HTTP URL, File Path, File Content and Mime Type.
These are all printed to the PS console, but there seems no way to get them into a file.
Not by a result object, not by transcripts, not by out-file, not by redirects.

**Comment by bseddon** [comment]
<<The object you are making just returns exactly the same as I can get redirected into a file with my method>>

No it doesn't.  The PS output of the object (the information that will be directed to a file) shows only a representation of the first level properties.   The information you are looking for is in the 'challenges' property which is a collection of other objects.

**Comment by ebekker** [comment]
You can see all of the properties in the object if you first pipe it to select, e.g.:
```
Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual | select *
```
or if you want to capture the return object so you don't lose a reference:
```
$x = Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual
$x | select *
```

**Comment by sdktr** [comment]
I'm facing the same problem, the token response for the manual method is not retrievable:

`$ChallengeInfo = ($completedChallenge = Complete-ACMEChallenge $identifierref -ChallengeType http-01 -Handler manual) 
== Manual Challenge Handler - HTTP ==
  * Handle Time:      [11/8/2016 12:30:49 PM]
  * Challenge Token:  [glRSjoXkiQWY9Rinpqz-C0K1dPQOBISEjqmvNgz3Fw8]
To complete this Challenge please create a new file
under the server that is responding to the hostname
and path given with the following characteristics:
  * HTTP URL:     [http://domain/.well-known/acme-challenge/glRSjoXkiQWY9Rinpqz-C0K1dPQOBISEjqmvNgz3Fw8]
  * File Path:    [.well-known/acme-challenge/glRSjoXkiQWY9Rinpqz-C0K1dPQOBISEjqmvNgz3Fw8]
  * File Content: [glRSjoXkiQWY9Rinpqz-C0K1dPQOBISEjqmvNgz3Fw8.H_bfElkGG4X4IHPJJeZGMHziUHgfL7w_w8BuQiQvoLU]
  * MIME Type:    [text/plain]
------------------------------------

$ChallengeInfo | select *

IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : domain
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/Cz-RYE9GECH2b7tau_00
Status         : pending
Expires        : 11/15/2016 11:29:10 AM
Challenges     : {, manual, }
Combinations   : {0, 2, 1}
`
Is the pre-0.8 method of adding Validation Handlers still usable in some way? I am pushing the tokeninfo to an external loadbalancer, so knowing where/how to retrieve the the file content would be great.

**Comment by bseddon** [comment]
You have to query the identifier object:

Run a command like:

((Get-ACMEIdentifier $alias).Challenges | Where-Object { $_.Type -eq 'http-01' }).ChallengePart

You will get the information you need.

@ebekker This question is asked frequently.  I think people do not see these past responses because they are closed but GitHub default is to show only open issues.  It might be worth adding a note to the Wiki,

**Comment by WallyRanson** [comment]
Well, I have been mingling a bit with it and this is what I came up with so far.
I am no PowerShell programmer and I am nowhere near done, but I have automated some of the steps done in the Quick Start guide and it might help others. :)
Currently I am a bit stuck on two issues.

1. I have no clue what encoding the response file must be in a that seem to have impact, I have tried UTF8 instead of unicode, which seems to be the default.

2. This is unrelated to ACMESharp, but it seems that my webserver default to MimeType "application/octet-stream" for files with no extensions and there is no way to change it through the options. Luckily the program have been made open source a few years back, so I just need to get a Visual Studio enviroment running and tackle that problem to rule that error possibility out before fighting on. :)

I will probably return with more questions later on, but for now: Thanks for the help!  👍 

-----------------------------------------------------------------------------
Import-Module ACMESharp

$DomainList = @("domain1.com", "domain2.net")
$FTPServer = "ftp.domain1.com"
$FTPUser = "Username"
$FTPPassword = "Password"
$WorkDir = ""c:\\Users\\Administrator\\Documents\\ACME"

# Create output directories, if this is the first time its run in the work directory
if ((Test-Path ($WorkDir+"\\1-Identifiers\\")) -eq $FALSE) {
    New-Item -ItemType directory -Path  ($WorkDir+"\\1-Identifiers\\")
}
if ((Test-Path ($WorkDir+"\\2-Challenges\\")) -eq $FALSE) {
   New-Item -ItemType directory -Path  ($WorkDir+"\\2-Challenges\\")
}

$TimeStamp = (Get-Date -Format s) -replace '-' -replace 'T' -replace ':'
ForEach ($Domain in $DomainList) {
    $Alias=($Domain.ToString() -replace "\.")+$TimeStamp

    # Create new ACMEIdentifier for the domain
    if ((Test-Path ($WorkDir+"\\1-Identifiers\\"+$Domain)) -eq $FALSE) {
        New-Item -ItemType directory -Path  ($WorkDir+"\\1-Identifiers\\"+$Domain)
    }
    New-ACMEIdentifier -Dns $Domain -Alias $Alias > ($WorkDir+"\\1-Identifiers\\"+$Domain+"\\"+$TimeStamp+".txt")
    Start-Sleep 5

    # Request new challenge for the domain
    if ((Test-Path ($WorkDir+"\\2-Challenges\\"+$Domain)) -eq $FALSE) {
        New-Item -ItemType directory -Path  ($WorkDir+"\\2-Challenges\\"+$Domain)
    }
    $result = Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual
    Start-Sleep 5

    # Create HTTP response file for challenge
    $Challenges = [Collections.Generic.List[Object]]($result.Challenges.ToArray())
    $ChallengeObj=($Challenges[($Challenges.FindIndex( {$args[0].Type -eq "http-01"}))])
    $ChallengeObj.Challenge.Answer.KeyAuthorization |Out-File -Encoding UTF8 ($WorkDir+"\\2-Challenges\\"+$Domain+"\\"+$ChallengeObj.Token)

    # Upload HTTP response file to webserver
    $ftp = [System.Net.FtpWebRequest]::Create($FTPServer+"/.well-known/acme-challenge/"+$ChallengeObj.Token)
    $ftp = [System.Net.FtpWebRequest]$ftp
    $ftp.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile
    $ftp.Credentials = new-object System.Net.NetworkCredential($FTPUser,$FTPPassword)
    $ftp.UseBinary = $true
    $ftp.UsePassive = $true
    $content = [System.IO.File]::ReadAllBytes($WorkDir+"\\2-Challenges\\"+$Domain+"\\"+$ChallengeObj.Token)
    $ftp.ContentLength = $content.Length
    $rs = $ftp.GetRequestStream()
    $rs.Write($content, 0, $content.Length)
    $rs.Close()
    $rs.Dispose()
    Start-Sleep 5

    # Submit the challenge for approval
    Submit-ACMEChallenge $Alias -ChallengeType http-01
}
-----------------------------------------------------------------------------

**Comment by WallyRanson** [comment]
Ok, the formating on this forum seems to have its own life. :)

**Comment by WallyRanson** [comment]
And BTW. what really help me was looking at the content of ACMESharp's vault file. :)

**Comment by WallyRanson** [comment]
This has been solved, so closing the issue. :)
