### ISSUE TITLE
Error code 9009 building latest and greatest

### ISSUE THREAD

**Issue by bseddon** [ebekker/ACMESharp#183]
Just download the latest source to be able to take a look at the option to remove Aliases.  When I build I get an error that the following command exited with code 9009:

"tools\XmlDoc2CmdletDoc\XmlDoc2CmdletDoc.exe ACMESharp\ACMESharp.POSH\bin\Debug\ACMESharp\ACMESharp.POSH.dll" 

The actual command is longer than this but I've cut out the environment specific stuff to make it readable though it is the environmental stuff that's causing the problem.  

I could not find any properties setting to change this command and based on the comment in the POSH project file, I'm guessing you added the command to run XmlDoc2CmdletDoc.exe to the after build event (line 169 of the project file).

I'm guilty of using projects in paths that contain spaces which is why the command fails for me.  Below is a small modification of the line to invoke XmlDoc2CmdletDoc.exe and the subsequent 'move' command.  You will see it adds four &quot; entities to each command so the generated command is quoted correctly when invoked.

```xml
<Exec Command="&quot;$(ProjectDir)..\..\tools\XmlDoc2CmdletDoc\XmlDoc2CmdletDoc.exe&quot; &quot;$(TargetPath)&quot;" />
<Exec Command="move &quot;$(TargetPath)-Help.xml&quot; &quot;$(TargetDir)en-US&quot;" />
```

**Comment by ebekker** [comment]
Just committed the change, glad you're guilty, it helps to root out issues like this :-)

I had just pushed a commit a few mins ago, but cancelled it to make sure that this change was captured in the next build on AV.

You should be able to update and confirm the changes are working for you, thanks!

**Comment by bseddon** [comment]
I can confirm the changes are working
