### ISSUE TITLE
Complete-ACMEChallenge throws exception when alias begins with a digit

### ISSUE THREAD

**Issue by rpresser-aleyant** [ebekker/ACMESharp#185]
`PS> New-ACMEIdentifier -Dns 360fcu.r2graphics.com -Alias 360fcu.r2graphics.com-23jlj23`
*identifier created successfully*

`PS> Complete-ACMEChallenge 360fcu.r2graphics.com-23jlj23 -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = "Default Web Site" }`

exception thrown as follows:
```
Complete-ACMEChallenge : Input string was not in a correct format.
At line:1 char:1
+ Complete-ACMEChallenge $alias -ChallengeType http-01 -Handler iis
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], FormatException
    + FullyQualifiedErrorId : System.FormatException,ACMESharp.POSH.CompleteChallenge
```

If I make sure the alias begins with a letter, the exception does not happen.

**Comment by ebekker** [comment]
That's by design, you can see why over [here](https://github.com/ebekker/ACMESharp/wiki/PowerShell-Module-Design#general).

**Comment by ebekker** [comment]
Added this *observation* to the FAQ.

**Comment by rpresser-aleyant** [comment]
Sorry and thank you
