### ISSUE TITLE
Extracting DNS challenge for auto provisioning

### ISSUE THREAD

**Issue by bluedoors** [ebekker/ACMESharp#187]
If undertaking a DNS Challenge Type as below

PS> Complete-ACMEChallenge dns1 -ChallengeType dns-01 -Handler manual
== Manual Challenge Handler - DNS ==
  * Handle Time:      [1/12/2016 1:41:51 PM]
  * Challenge Token:  [xfc0oQahXVqdaBlcZbk5nL8H-GSDFCoQ8LGzOL07qVI]
To complete this Challenge please create a new Resource
Record (RR) with the following characteristics:
  * RR Type:  [TXT]
  * RR Name:  [_acme-challenge.example.com]
  * RR Value: [vNx_fpLgvq0l4rqSATuxhxl9pa155SoeKvNZ98AFB_4]
------------------------------------

How can i in powershell reference the RR Type, Name and Value, so i can utilise them in subsequent calls to Azure DNS to populate the DNS, thus removing this manual step.

**Comment by animetauren** [comment]
Been working on this part myself, check this [gist](https://gist.github.com/animetauren/9b7e5e9e045c0667f3a89cba0e59dae5) i created, tried formatting the code in the text but failed at it. 

Let me know if it works, been working on updating my current ACME Azure Script with support for Azure DNS and would love for someone to test this part for me.

**Comment by ebekker** [comment]
It looks like @animetauren's [gist](https://gist.github.com/animetauren/9b7e5e9e045c0667f3a89cba0e59dae5) is on the right track.  The manual handler was initially intended to be used by *manual* consumption -- that is some user looking at the response message and acting upon it manually.

But I've definitely gotten feedback to support a machine digestible format as well, so what I'm thinking is that I can add a parameter flag to the Manual handler that will allow spitting out JSON or PowerShell object (which can be easily JSONified) to be easily captured and whose elements can be easily referenced.

This will definitely be useful in some of the ideas being tossed around in #182.

**Comment by ebekker** [comment]
I'll add this flag into the current pending release if no one else gets to it first.

**Comment by bluedoors** [comment]
Thanks @animetauren that's helped greatly.
I've forked the [gist](https://gist.github.com/bluedoors/db9f6a4f9bfd8f7cda0926a2419584b8), and modified it slightly - one to meet my requirement of SAN certs, but also to correct two items:
1. The challenge provides the FQDN for the DNS entry, yet Azure wants it minus the root domain, eg example.com. So i've used a trimEnd() function
2. The Azure DNS api's listed a depreciation warning, so i updated it

It successfully captures the challenge and sets it in Azure DNS.

note: please excuse any poor Powershell coding - only started using it last week.

**Comment by mamama1** [comment]
why not simply do this?

`$recordname = ((Update-ACMEIdentifier "LE-$domainname" -ChallengeType dns-01).Challenges | Where-Object {$_.Type -eq "dns-01"} | select Challenge -ExpandProperty Challenge).RecordName
$recordvalue = ((Update-ACMEIdentifier "LE-$domainname" -ChallengeType dns-01).Challenges | Where-Object {$_.Type -eq "dns-01"} | select Challenge -ExpandProperty Challenge).RecordValue`

Works perfectly for me, already automated this.

**Comment by bluedoors** [comment]
Able to share your code?

**Comment by ebekker** [comment]
Manual Challenge Handler has been updated with a new `OutputJson` parameter that spits out the handling details as JSON blob for easier parsing.  See #270 for details.
