### ISSUE TITLE
Import-Module fail Window2012R2

### ISSUE THREAD

**Issue by demethan** [ebekker/ACMESharp#192]
Following the instructions on the wiki. 

![image](https://cloud.githubusercontent.com/assets/5810363/20810992/f573fe14-b7d9-11e6-94e4-e681c16e95e1.png)

Sorry OS is in french.

**Comment by ebekker** [comment]
What version of PowerShell?  Also, was ACMESharp installed from the PS Gallery?

**Comment by demethan** [comment]
I did the manual install.  I extracted the zip and took the ACMESharp folder. dumped it the module folder under system32 like the instruction said. 

![image](https://cloud.githubusercontent.com/assets/5810363/20838587/3f0ab804-b877-11e6-8e45-0d0a606ff2cc.png)

**Comment by ebekker** [comment]
Could you try to install from the PS Gallery?  That version is more up-to-date and current.

```PowerShell
Install-Module ACMESharp
```

You'll be prompted to accept the repo, but can safely accept that.

**Comment by demethan** [comment]
That worked good.  Now to figure out how to work this. Always get a status: invalid.
