### ISSUE TITLE
Forum for users

### ISSUE THREAD

**Issue by WallyRanson** [ebekker/ACMESharp#194]
We kind of need a forum for user-to-user help.
Like posting script examples and so on.

I have made a script that gets a SAN certificate for my exchange server and then installs it.
Maybe I have made the FTP installation also (I realized that I did not use IIS for FTP, when I tried to test it. :))

Script is below
-----------------------------------------------------------------------------------------------------------
`
cls
Import-Module ACMESharp

# User controlled variables
$DomainList = @("MyDomain.com", "www.MyDomain.com", "owa.MyDomain.com", "autodiscover.Mydomain.com", "ftp.MyDomain.com") # First entry will be the main domain in the certificate, the rest will be SANs. This script requires atleast 2 domains, because it tries to retrieve a SAN Certificate.
$WorkDirectory="c:\\Users\\Administrator\\ACME" # This folder must exist already
$FTPSite="ftp://ftp.MyDomain.com/ACME/.well-known/acme-challenge/"
$FTPUser="MyFTPUsername"
$FTPPass="MyFTPPassword"
$CertPass="MyPFXCertificatePackagePassword"

# Script controlled variables
$SANList=@()
$AltIdRefs=@()
$RuntimeError=0

ForEach ($Domain in $DomainList) {
    if ($RuntimeError -ne 0) {break}
    do {
        $TimeStamp = (Get-Date -Format s) -replace '-' -replace 'T' -replace ':'
        $Alias=($Domain.ToString() -replace "\.")+$TimeStamp

        # Create new ACMEIdentifier for the domain
        if ((Test-Path ($WorkDirectory+"\\1-Identifiers\\"+$Domain)) -eq $FALSE) {
            New-Item -ItemType directory -Path  ($WorkDirectory+"\\1-Identifiers\\"+$Domain)
        }
        New-ACMEIdentifier -Dns $Domain -Alias $Alias > ($WorkDirectory+"\\1-Identifiers\\"+$Domain+"\\"+$TimeStamp+".txt") 
        Start-Sleep 10

        # Request new challenge for the domain
        if ((Test-Path ($WorkDirectory+"\\2-Challenges\\"+$Domain)) -eq $FALSE) {
            New-Item -ItemType directory -Path  ($WorkDirectory+"\\2-Challenges\\"+$Domain)
        }
        $result = Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual
        Start-Sleep 10

        # Create HTTP response file for challenge
        $Challenges = [Collections.Generic.List[Object]]($result.Challenges.ToArray())
        $ChallengeObj=($Challenges[($Challenges.FindIndex( {$args[0].Type -eq "http-01"}))])
        $ChallengeObj.Challenge.Answer.KeyAuthorization |Out-File -Encoding ascii ($WorkDirectory+"\\2-Challenges\\"+$Domain+"\\"+$ChallengeObj.Token)

        # Upload HTTP response file to webserver
        $ftp = [System.Net.FtpWebRequest]::Create($FTPSite+$ChallengeObj.Token)
        $ftp = [System.Net.FtpWebRequest]$ftp
        $ftp.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile
        $ftp.Credentials = new-object System.Net.NetworkCredential($FTPUser,$FTPPass)
        $ftp.UseBinary = $true
        $ftp.UsePassive = $true
        $content = [System.IO.File]::ReadAllBytes($WorkDirectory+"\\2-Challenges\\"+$Domain+"\\"+$ChallengeObj.Token)
        $ftp.ContentLength = $content.Length
        $rs = $ftp.GetRequestStream()
        $rs.Write($content, 0, $content.Length)
        $rs.Close()
        $rs.Dispose()
        Start-Sleep 10

        # Submit the challenge for approval
        Submit-ACMEChallenge $Alias -ChallengeType http-01

        # Wait for status update on challenge
        $Cycles=0
        # Check Status each minute for 5 minutes
        do {
            if ($Cycles -eq 5) {break}
            start-Sleep 60
            $AllStatus=Update-ACMEIdentifier $Alias -ChallengeType http-01
            $Status = [Collections.Generic.List[Object]]($AllStatus.Challenges.ToArray())
            $StatusObj=($Status[($Status.FindIndex( {$args[0].Token -eq $ChallengeObj.Token}))])
        } while ($StatusObj.Status -eq "pending")
    # If status is still pending, then setup new challenge
    } while ($StatusObj.Status -eq "pending")
    
    # if status is invalid then stop challenges
    if ($StatusObj.Status -eq "invalid") {
        $RuntimeError=1
        break
    }

    # Add alias to array of approved domains
    $SANList+=$Alias
    if ($SANList.Length -ne 0) {
        $AltIdRefs+=$Alias
    }

}

# if no errors then get certificate
if ($RuntimeError -eq 0) {
    $CertName="Exch"+$TimeStamp
        
    $TimeStamp = (Get-Date -Format s) -replace '-' -replace 'T' -replace ':'
    New-ACMECertificate $SANList[0] -Generate -AlternativeIdentifierRefs $AltIdRefs -Alias $CertName
    start-Sleep 10
    Submit-ACMECertificate $CertName
    do {
        start-Sleep 10
        $CertResult = Update-ACMECertificate $CertName
    } while ($CertResult.IssuerSerialNumber -eq "")

    #Export issuer certificate
    # Get-ACMECertificate $CertName -ExportIssuerPEM $WorkDirectory"\\3-Certificates\\Issuer"$CertName".crt.pem" -ExportIssuerDER $WorkDirectory"\\3-Certificates\\Issuer"$CertName".crt"

    # Export private key in PEM-format
    # Get-ACMECertificate $CertName -ExportKeyPEM $WorkDirectory"\\3-Certificates\\"$CertName".key.pem"

    # Export certificate signing request(CSR) in PEM-format
    # Get-ACMECertificate $CertName -ExportCsrPEM $WorkDirectory"\\3-Certificates\\"$CertName".csr.pem"

    # Export Certificate in PEM-format
    # Get-ACMECertificate $CertName -ExportCertificatePEM $WorkDirectory"\\3-Certificates\\"$CertName".crt.pem"

    # Export PKCS#12 (PFX) Archive
    Get-ACMECertificate $CertName -ExportPkcs12 $WorkDirectory"\\3-Certificates\\"$CertName".pfx" -CertificatePassword $CertPass

    # Add exchange management powershell module and setup certificate for exchange services.
    Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
    start-Sleep 10
    Import-ExchangeCertificate -Filename $WorkDirectory"\\3-Certificates\\"$CertName".pfx" -Password (ConvertTo-SecureString -String $CertPass -AsPlainText -Force)|Enable-ExchangeCertificate -Services "IIS,IMAP,POP,SMTP" -Force

    # Add web management powershell module and setup certificate for iis services (Not tested yet)
    # Import-Module -Name WebAdministration
    # Import-PfxCertificate -FilePath $WorkDirectory"\\3-Certificates\\"$CertName".pfx" Cert:\LocalMachine\my -Password (ConvertTo-SecureString -String $CertPass -AsPlainText -Force)
    # Set-ItemProperty -Path "IIS:\Sites\Default Web Site" -Name ftpServer.security.sslCertHash -Value $CertResult.Thumbprint

}
`

**Comment by ebekker** [comment]
There are [Community Forums](http://groups.google.com/group/acmesharp) that have been posted on the project's [home](https://github.com/ebekker/ACMESharp) from almost the beginning.  Feel free to use it!

**Comment by WallyRanson** [comment]
Ok, found it, but its a bit hidden away.
Normally you would look for something like that in the top menu, so putting it in there would be great.
Also a page on the Wiki with a reference to it would improve its usage.
Lastly a little indexing of the forum might be good too, like Announcements, General Discussions, Code Examples, Coding Help and so on.

**Comment by ebekker** [comment]
Top menu?  What menu are you referring to?

**Comment by WallyRanson** [comment]
The one with Code, Issues, Pull Requests, Projects, Wiki and so on.

**Comment by ebekker** [comment]
I don't have control over those tabs, unless you know of a trick to add to GitHub?

**Comment by WallyRanson** [comment]
I feared you had no controls over the top menu, but its a lot more clear now on the Wiki page. :)

I am not much for tags in multiuser settings, because they often become mixed up, like tagging the word "help" in two different categories for "needing help" and tagging it for "providing coding help" or using tags like "code", "example", "help" and all the commands for code examples.
But Google groups is what Google group is, so its better than nothing. :)
