### ISSUE TITLE
Any chance of an 0.8.2 release on PowerShell Gallery?

### ISSUE THREAD

**Issue by whereisaaron** [ebekker/ACMESharp#199]
Hi the last ACMESharp release was Jan 2016 and some major features like an IIS installer have been added since then. The build has been bumped to 0.8.2, it that version stable enough to make a release?

**Comment by whereisaaron** [comment]
Failing a release, is there a practical way to install/use the Appveyor artifacts from PowerShell?

https://ci.appveyor.com/project/ebekker/acmesharp/build/artifacts

**Comment by ebekker** [comment]
Hi @whereisaaron, I'm still not quite ready to promote the current builds to a release yet, but you can access them from the STAGING NuGet feed:  https://www.myget.org/gallery/acmesharp-posh-staging

These are updated every time the latest code is successfully built by AppVeyor.

**Comment by whereisaaron** [comment]
Thanks for the tip @ebekker.

**Comment by zowers** [comment]
it would be great to describe how to install the staging version from myget in https://github.com/ebekker/ACMESharp/wiki/Quick-Start
