### ISSUE TITLE
IIS 10 on WS2016 - Automated checks for extensionless content failed.

### ISSUE THREAD

**Issue by IMBACalimba** [ebekker/ACMESharp#200]
Hello everybody,

first of all i hope that im here in the right place for my problem.

My problem is that since yesterday i try to use the tool "certify", but always when i request a new certificate i get the following error message.

>**Automated checks for extensionless content failed. Authorisations will not be able to complete. Change the web.config in <your site>\.well-known\acme-challenge and ensure you can browse to http://<your site>/.well-known/acme-challenge/configcheck before proceeding.**

The funny thing is that i can browse the directory in my browser and i also can open the files which "certify" creates in my browser without any problems.

I also unticked the box "Auto create/update IIS bindinds" but anyway i think i has absolutely nothing to do with this, but at least i tried it :)

I'm using IIS10 (Windows Server 2016) and also added the mimetype ".*" to my site, also tried to edit the **web.config** and use `".*"` instead of `"."` .

Here is the **web.config** which i created automatically by "**certify**"

`<?xml version = "1.0" encoding="UTF-8"?>
<configuration>
<system.webServer>
<staticContent>
<mimeMap fileExtension="." mimeType="text/plain" />
</staticContent>
</system.webServer>
</configuration>`

So if anyone has an idea or something how i get rid of it i would very appreciate the help!

Best regards
IMBA

**Comment by ebekker** [comment]
Sorry, wrong project, try [Certify](https://github.com/webprofusion/Certify) instead.  ACMESharp is just a library used by Certify.
