### ISSUE TITLE
New-ACMECertificate : Access to the path '<vault path>\GUID-key.pem' is denied

### ISSUE THREAD

**Issue by BGleasonGH** [ebekker/ACMESharp#203]
So yeah, I hate to even be asking this because first things first your going to ask, "did you check your perms..?" That answer would be yes, I have tried inherited perms, explicit perms, I have made myself an owner of the folder and I can write files and folders in there all day long, but every time I try to generate a new certificate I get the listed error, 

```
PS C:\Users\administrator> New-ACMECertificate -IdentifierRef <Alias> -KeyPemFile <Path to>.key -CsrPemFile <Path to>.csr -Alias <New-ACMECert Alias>
New-ACMECertificate : Access to the path 'C:\ProgramData\ACMESharp\sysVault\45-KEYPM\e8c8b997-eec8-4eab-a22e-cd9d8feb73e3-key.pem' is denied.
At line:1 char:1
+ New-ACMECertificate -IdentifierRef <Alias> -KeyPemFile E:\Apa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMECertificate], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,ACMESharp.POSH.NewCertificate
 

PS C:\Users\administrator> 
```

Any thoughts, anything in <> is just obfuscated...

**Comment by BGleasonGH** [comment]
Note, I have also tried with an alternate account that has admin permissions and still received the same error... Just in case it had to do with security limitations imposed on the "Administrator" account...
Thanks...

**Comment by WallyRanson** [comment]
Make sure you have read, modify and write permissions to all sub-objects, both folders and files.
Find the exact file mentioned and check that this is the case.
Windows is really bad at replacing permissions on files and folders, if you try to change it from the top and it changes several times down the hierarchy.

**Comment by rstaub77** [comment]
Hi,

I just had the same error at the same step (45/pem generation) using Certify.
When reading the Certify source code, I noticed these lines of code :
```
                            var keyGenAsset = vlt.CreateAsset(VaultAssetType.KeyGen, keyGenFile, getOrCreate: force);
                            var keyPemAsset = vlt.CreateAsset(VaultAssetType.KeyPem, keyPemFile, isSensitive: true, getOrCreate: force);
                            var csrGenAsset = vlt.CreateAsset(VaultAssetType.CsrGen, csrGenFile, getOrCreate: force);
                            var csrPemAsset = vlt.CreateAsset(VaultAssetType.CsrPem, csrPemFile, getOrCreate: force);
```
So it seems that specifically for the PEM file, the option "isSensitive" is used.
I tried to rebuild without this option, and then the process succeded to completion.
Maybe There is a problem with the syntax of the ProgramData filename.
By the way I am not sure about the purpose of the isSensitive option, as it seems to works fine without it.

**Comment by ebekker** [comment]
The default Vault provider (`local`) interprets the `isSensitive` flag by saving those files using EFS, which is not available under some circumstances, such as a non-NTFS file system or non-business versions of Windows, like Win 10 Home.

You can disable the attempt to use EFS by setting the Vault provider's parameter **`BypassEFS`** to `true`.

**Comment by rstaub77** [comment]
Thank you for this explanation.
As a matter of fact it is a 2008 server and a domain member, but I thinks EFS has been blocked by admins via GPO, that would explain the error tied to this fonctionality.

**Comment by ebekker** [comment]
You're welcome.  If you switch back to using the distributed version of the code (instead of you using your custom-built version) and simply set the *`BypassEFS`* parameter, it should work correctly for you.  If you go this route, let me know so we can confirm everything works as expected.

**Comment by ebekker** [comment]
This issue and the solution are more fully documented [here](https://pkisharp.github.io/ACMESharp-docs/Local-Vault-EFS).
