### ISSUE TITLE
Submit-ACMEChallenge : challenge has not been decoded

### ISSUE THREAD

**Issue by kirillkovalenko** [ebekker/ACMESharp#204]
I'm following the tutorial, and have `Submit-ACMEChallenge : challenge has not been decoded` error upon submitting the challenge. I've tried running with the -Verbose switch but got the same result. What else can I do to troubleshoot?

**Comment by animetauren** [comment]
@kirillkovalenko which challenge method are you using? also have you checked the status of the challenge from LE's site itself?

Normally the link to the LE url for the challenge is displayed when you run the following:

```powershell
Complete-ACMEChallenge
```

**Comment by kirillkovalenko** [comment]
I cannot reproduce it any more, so I'm closing the issue.

**Comment by ebekker** [comment]
I assume this was against the LE production site, not their STAGE site, correct?  Could have been a temporary hiccup in their service.

**Comment by kirillkovalenko** [comment]
That right, it was production. Could be hiccup, because that day we had problems with http-01 type validation despite correct web.config.

**Comment by ericwj** [comment]
I'm getting this too.

`Complete-ACMEChallenge -IdentifierRef $id -HandlerProfileRef http-01` will produce
```PS
Complete-ACMEChallenge : Object reference not set to an instance of an object.
At line:1 char:1
+ Complete-ACMEChallenge -IdentifierRef beta -HandlerProfileRef http-01
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,ACMESharp.POSH.CompleteChallenge
```
