### ISSUE TITLE
All challenge types are 'pending', but none of them have an actual challenge

### ISSUE THREAD

**Issue by masbicudo** [ebekker/ACMESharp#205]
I have created a small C# application to help-me creating a certificate using LetsEncrypt.
It did work the first time, and I could get a valid certificate for my domain.

The problem happens when I then try to generate another certificate for another domain.
After calling `CompleteChallenge`, with a new `Identifier` "dns2" ("dns1" was used to register the first domain), it returns an `AuthorizationState` that has 3 challenges, but none of them have an actual challenge inside. I mean each of them have the property `Challenge` set to null.

What could be wrong?

**Comment by ebekker** [comment]
Just to clarify, you are not using the PowerShell module to do this -- you're strictly using the ACMESharp library to write you're own client, correct?

You can try to update the challenge data after you submit it to refresh the content.  So, the first attempt worked as expected and there was challenge content after the initial submit?

**Comment by masbicudo** [comment]
I am using the PowerShell module. What I do is create the `Cmdlet`s and call `Invoke` on them. I did it this way because I found code to do it using power shell on the internet, but I wanted to use C#, windows forms, and a simplistic interface, to allow me to create the certificate in a very fast way. My use case is for static page providers like GitLab, and GitHub (when it supports custom domains with HTTPS).

The project is this one... https://github.com/masbicudo/LetsEncrypt-Certificate-Creator

The interesting thing is that not even the URL at LetEncrypt API shows the data, I mean, the returned JSON for each of the 3 challenge types are trivial:

dns-01:
```
{
  "type": "dns-01",
  "status": "pending",
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/2sMlHSHe1KUkjrkp9r2IqZbiCWAM1_2j3N1TMp55gTI/499617476",
  "token": "v8Wu3Ms_FGHSapq52dpzcEeW3qfvrMROgwSPucR_iW4"
}
```

http-01:
```
{
  "type": "http-01",
  "status": "pending",
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/2sMlHSHe1KUkjrkp9r2IqZbiCWAM1_2j3N1TMp55gTI/499617475",
  "token": "OK8RB2pAjtSMQhq89a_cnTN0HEv7EEN-erX0qMBHQ5I"
}
```

tls-01:
```
{
  "type": "tls-sni-01",
  "status": "pending",
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/2sMlHSHe1KUkjrkp9r2IqZbiCWAM1_2j3N1TMp55gTI/499617474",
  "token": "5uu_pF21dhtvhmpzD2pnZGbSxyrb9CzaFK2a25-uVhQ"
}
```

**Comment by masbicudo** [comment]
Sorry, I forgot to answer your last question: yes, the first attempt worked.

To complement, the code I found was this one: https://gist.github.com/nul800sebastiaan/31b000874ffa69f4c0af

**Comment by ebekker** [comment]
I'm a little lost in your code sample.  It looks like you're trying to use git submodules to include the ACMESharp library?  You might be better off importing nuget packages of the dependent libraries.  You can take a look at [this other project](https://github.com/webprofusion/Certify) which wraps a GUI around ACMESharp (I believe it's WPF, not WinForms).

**Comment by masbicudo** [comment]
I included as a submodule because of some errors when using it from Nuget.
The plugin system tries to load an assembly `ManagedOpenSsl64`, and throws a `BadImageFormatException`. This error does not happen when I am using project references.

I'll take a look at that project to see if I can learn something from it.
Thanks!

**Comment by masbicudo** [comment]
Sorry... this was my fault... I'm ashamed. =D
I was not calling `CompleteChallenge`, I reused a piece of code that was like this:

    state = state ?? new NewIdentifier { Dns = registrationOptions.Domain, Alias = idref }.GetValue<AuthorizationState>();

and replaced the new NewIdentifier part like this:

    state = state ?? new CompleteChallenge { Handler = "Manual", IdentifierRef = idref, ChallengeType = "http-01" }.GetValue<AuthorizationState>();

I just can't believe it... feeling very stupi right now!!!
Thanks for your support.
