### ISSUE TITLE
New-ACMEIdentifier throws exception with or without complete command

### ISSUE THREAD

**Issue by jhansgit** [ebekker/ACMESharp#211]
PS C:\WINDOWS\system32> New-ACMEIdentifier
New-ACMEIdentifier : Das Objekt des Typs "System.Net.FileWebRequest" kann nicht in Typ "System.Net.HttpWebRequest"
umgewandelt werden.
In Zeile:1 Zeichen:1
+ New-ACMEIdentifier
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMEIdentifier], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,ACMESharp.POSH.NewIdentifier

PS C:\WINDOWS\system32> **New-ACMEIdentifier -Dns dns1111 -Alias azurewebapp.csc-cic.com -Label "Azure WebApp"**
New-ACMEIdentifier : Das Objekt des Typs "System.Net.FileWebRequest" kann nicht in Typ "System.Net.HttpWebRequest"
umgewandelt werden.
In Zeile:1 Zeichen:1
+ New-ACMEIdentifier -Dns dns1111 -Alias azurewebapp.csc-cic.com -Label ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMEIdentifier], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,ACMESharp.POSH.NewIdentifier

Any idea? It worked before.

Thanks
Joachim

**Comment by ebekker** [comment]
Looks like there is some illegal cast going on from FileWebRequest to HttpWebRequest -- are you talking to the right Let's Encrypt Endpoing?

**Comment by jhansgit** [comment]
As I said it worked before, so I already got valid cerificates. It's weired that the illigal cast exception is thrown when I run the command without any parameters. How can I cast the expression? Which expression is illegal casted? Not sure what you exactlly mean by "Let's Encrypt Endpoint", I only wonna create a new certificate starting with a new identifier....

**Comment by jhansgit** [comment]
I played around with different vaults, so I reinstalled the module, deleted the default vault and started over again. All fine now. Thanks
