### ISSUE TITLE
Erro On Importing ACMESharp Module

### ISSUE THREAD

**Issue by mostafazs** [ebekker/ACMESharp#212]
Hello
I'm new on getting certificate.
I try to get certiicate for a free hosting that provide uploading certificate on cPanel.
Use this [ACMESharp-Quick-Start](https://github.com/ebekker/ACMESharp/wiki/Quick-Start) and use ACMESharp on windows 7.
I can't install ACMESharp from Windows PowerShell Command Line instead install it manually accounding to previously wiki page, by downloading ACME-posh.zip file.

Now after copy ACME-posh.zip files on C:\Windows\System32\WindowsPowerShell\v1.0\Modules
and try to load module using command Import-Module ACMESharp i get this error: 

`Import-Module : The 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ACMESharp\ACMESharp.psd1' module cannot be impo
rted because its manifest contains one or more members that are not valid. The valid manifest members are ('ModuleToPro
cess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVersio
n', 'PowerShellHostName', 'PowerShellHostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'Re
quiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleL
ist', 'FileList', 'FunctionsToExport', 'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the members t
hat are not valid ('RootModule', 'DefaultCommandPrefix'), then try to import the module again.
At line:1 char:14
+ import-module <<<<  ACMESharp
    + CategoryInfo          : InvalidData: (C:\Windows\syst...\ACMESharp.psd1:String) [Import-Module], InvalidOperatio
   nException
    + FullyQualifiedErrorId : Modules_InvalidManifestMember,Microsoft.PowerShell.Commands.ImportModuleCommand
`

![powershell_acmesharp_error](https://cloud.githubusercontent.com/assets/12104405/22097332/d7cfeb3e-de35-11e6-8941-b923f993505d.png)

Thanks.

**Comment by drsox** [comment]
What is the result of the command
Get-Host

**Comment by ebekker** [comment]
@mostafazs, I repeated these steps on a Win2012R2 host and a Win2016 and it was successful for me.

You said you were on Win7 and based on your screenshot of PowerShell window (Copyright 2009) I'm guessing you're using the version of PowerShell that ships with Win7 which is PowerShell v2.  This is too old for ACMESharp, you need to upgrade to a more recent version of PowerShell:

https://www.microsoft.com/en-us/download/details.aspx?id=50395

**Comment by mostafazs** [comment]
sorry for late replay.
@drsox  

result of `Get-Host` Command:

`Name             : ConsoleHost
Version          : 2.0
InstanceId       : 1f45b1aa-27c4-48d4-ad2b-aeea5572538c
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace`

@ebekker 
Thanks. I try it.

**Comment by ebekker** [comment]
I'm going to close this for now, if you still have problems after upgrading, you can reopen and continue discussion.

**Comment by CarlGalloy** [comment]
Hi,
I have same problem.
I read Requirement section on wiki. I have .Net4.5 WMF 4 that included `Power Shell 4` but now we get below error when use command: `Import-Module ACMESharp`

"
Import-Module : Could not load file or assembly
'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ACMESharp\ACMESharp.POSH.dll' or one of its dependencies.
Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module ACMESharp
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
"

My PowerShell Information by do this cmdlet : `$PSVersionTable`


`
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18408
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
`
![import-error](https://user-images.githubusercontent.com/30363721/28489283-e9da7bb0-6ed5-11e7-80f6-d97fe0ede759.png)

**Comment by matiasdipaolo** [comment]
Hi,
I have same problem.  Like ↑↑↑↑↑↑↑↑↑↑↑

**Comment by animetauren** [comment]
This command runs just fine on my machine, the only difference i see is i am using PowerShell V5.1, i would encourage you upgrade and try that

**Comment by ebekker** [comment]
This issue is now being tracked in #265
