### ISSUE TITLE
 a certificate for multiple domains

### ISSUE THREAD

**Issue by RuiHanDong** [ebekker/ACMESharp#214]
Can I apply for a certificate for multiple domains ? such as www.crdata.cn, crdata.cn
PS> New-ACMEIdentifier -Dns www.crdata.cn  -Alias dns1
PS> New-ACMEIdentifier -Dns crdata.cn  -Alias dns1

**Comment by WallyRanson** [comment]
Read the Quick Start Wiki.
Step 7 is the one solving your issue. :)

https://github.com/ebekker/ACMESharp/wiki/Quick-Start

**Comment by RuiHanDong** [comment]
thanks ,I got it.
