### ISSUE TITLE
Get http challenge manually

### ISSUE THREAD

**Issue by plitter** [ebekker/ACMESharp#218]
I'm trying to do the manual challenge automatically and I can't figure out how to get the values from complete challenge. I've tried to redirect the output to a variable with $var = Complete..., Complete... -outvariable test, and redirect(grasping at straws). To file with Complete... -HandlerParameters @{ WriteOutPath=C:\Certificates\manual.txt }(with and without quotes around path), Complete... | Out-File, some redirect options, but no luck.

I do think that WriteOutPath should have worked so I'm setting it as a bug :)

**Comment by animetauren** [comment]
This is what i normally use:

```powershell
$compACMEChall = Complete-ACMEChallenge $identifierRef -ChallengeType http-01 -Handler manual
```
If you would like check out the script i built on my [repo](https://github.com/animetauren/ACMEAzure), i get the output from the ACMEChallenge and do some processing of it.

**Comment by WallyRanson** [comment]
I did the following.

// Get the Challenge request
$result = Complete-ACMEChallenge $Alias -ChallengeType http-01 -Handler manual

// Find which challenge that should be answered
$Challenges = Collections.Generic.List[Object]
$ChallengeObj=($Challenges[($Challenges.FindIndex( {$args[0].Type -eq "http-01"}))])

// Make the challenge file by getting values from the $ChallengeObj
$ChallengeObj.Challenge.Answer.KeyAuthorization |Out-File -Encoding ascii ($Directory+"\"+$ChallengeObj.Token)

**Comment by ebekker** [comment]
Closing as the solution by @WallyRanson  should suffice, if you have any more problems you can reopen.

**Comment by plitter** [comment]
My thought was that I should redirect all certificates to one site. So instead of making a custom path /challenges/ I'll just use the normal one and then I don't need the manual method :)

**Comment by WallyRanson** [comment]
If you have domain1.com, domain2.com and domain3.com, then you can configure your server and DNS configuration, so domain1.com, domain2.com and domain3.com points to the same site and then just put the challenges there.
You might also be able configure your server, so domain1.com/.well-known/acme-challenge/ , domain2.com/.well-known/acme-challenge/ and domain3.com/.well-known/acme-challenge/ is the same directory on the server, but the rest of the sites are different.
This all depends on your configuration of the third party services.

If your are thinking that challenges for domain1.com, domain2.com and domain3.com all can be answered by domain1.com/.well-known/acme-challenge/ then its not possible.
Each domain MUST answer its own challenge, which is done to prove LE that you have control of the domain.

**Comment by plitter** [comment]
Sorry for late answer. @WallyRanson I would say that this is wrong. I've read that you can redirect to another site if you want to, and I tested this by doing manual challenge to one site and adding the challenge in the correct path there. To be fair here I did only reissue the challenge and it was already valid. So might have been caching involved. Checkout https://letsencrypt.org/docs/integration-guide/ at "Picking a Challenge Type" and "Central Validation Servers"

**Comment by WallyRanson** [comment]
The redirection mentioned still means you have to set up your domain to answer the challenge.
The answer is just a redirect reply on that domain to check somewhere else specified in the redirect.
The domain MUST answer the challenge.

If that was not the case, then I could make a request for gmail.com and make fakesite.com answer it, which would then give me a valid certificate for gmail.com.

**Comment by plitter** [comment]
Correct me if I'm wrong here. The way it works is that domain.com/.well-known/challenge/x is requested from domain.com, that request is redirected to domain.org/something/x and a new request is sent to someotherdomain.org/x and letsencrypt verifies the content and if its the same as the challenge sets the challenge as true. From what I understand is that if google.com/.well-known/acme-challenge/x redirects you to fakesite.com/x you will get the certificate for google.com. Which means that you can redirect all such challenges to domain1.com/.well-known/acme-challeng/x from domain2.com/...., domainN.com/.... and it will still verify.

**Comment by WallyRanson** [comment]
Sounds right.

If you can set up a redirect at google.com/.well-known/acme-challenge/x, then you can verifiy ownership over google.com because it responded, although with a redirect and assuming the site that it redirected to have the right answer.
