### ISSUE TITLE
Cleanup temporal files

### ISSUE THREAD

**Issue by fpeterson194** [ebekker/ACMESharp#228]
Hi everyone!

I´m making some cleanup of the files produced after the certificate´s issuing. I notice the following:

1.\.well-known\acme-challenge
2. certificate folder where you extract it (if the certificate is already imported in your store you might want to delete it too. This will depend on your needs, of course).
3. C:\ProgramData\ACMESharp\sysVault

My questions are:

a) Am I missing some other folder where temp information is stored?
b) Regarding the path listed in point 3), I have several folders created, which of them are not needed? I know that "00-VAULT" and ".acme.vault" must remain right? What about the other folders?

Thanks!

**Comment by WallyRanson** [comment]
1. can be deleted without problems once the challenge has been validated.

2. the certificate might be a good idea to delete or atleast make sure its secured in any way possible, because, depending on what you have extracted, this might be used to make fraudulent web services if it falls in the wrong hands. Deletion or moving to an offline media is advised.

3. I would be very careful with making direct file access to this folder, because there might be files with references to the folders and files that needs to be updated when file and folders are changed in here.
I think ebekker is coming up with features to cleanup the vault through standardized powershell commands and its probably the best way, because he knows how the vault functions, both now and in the future.

**Comment by ebekker** [comment]
After you've submitted a Challenge response, you can clean-up the Challenge remnants using the `-Cleanup` flag.

For example, you would do things in this order (most of the params are removed for brevity):

```PowerShell
PS> Complete-ACMEChallenge
PS> Submit-ACMEChallenge
PS> Complete-ACMEChallenge -CleanUp
```

Every Challenge-handling provider has optional support for a CleanUp operation, and specifying this flag will invoke it.  In the case of the IIS provider it will delete the files in creates.  In the case of the AWS R53 provider, it will delete the DNS records it creates.

**Comment by fpeterson194** [comment]
@WallyRanson thanks very much for your response!

@ebekker thanks very much too!! So for the acme-challenge folder, I can clean it up with the -CleanUp parameter, right?
How about the C:\ProgramData\ACMESharp\sysVault? All the files there are needed or only 00-VAULT" and ".acme.vault" must remain? Do you have other way to clean them?
Thanks!!

**Comment by ebekker** [comment]
The files in the Vault don't get cleaned up -- it's a permanent record of all the activity that ACMESharp performs against an ACME server (i.e. Let's Encrypt) and it also holds the secret assets, i.e. your private key for the LE Registration and the private keys for any certificates.  So in that respect, the assets in the Vault only *grow*.

The Vault is typically very small, but if you want to get rid of it for some reason, you can just blow it away assuming you've exported all of your certificate components (private key and public cert).  You may also want to pull out the registration private key if you want to perform any subsequent operations against LE.

**Comment by fpeterson194** [comment]
@ebekker thanks very much for your reply! My goal is to minimize the files needed and keep only the ones that need in order to work.

I review each folder in the sysVault and I can notice the following (please correct me if I´m wrong):

30-CSRDT - CSRDetails in clear text for my requests (.json)
40-KEYGN - PrivKeys files (.json) PrivKeys for my generated certificates?
45-KEYPM - PrivKeys files (.pem)  Idem above
50-CSRGN - Empty files ({} content) (.json)
55-CSRPM - CSR files (.pem) for my generated certificates
65-CRTPM - CRT files for my generated certificates
66-CRTDR - DER files for my generated certificates (no privKey embebed)
75-ISUPM - PEM for Intermediate let´s encrypt CA
76-ISUDR - DER for Intermediate let´s encrypt CA
00-VAULT - All information about challenges done

I understand that 00-VAULT, 00-VAULT.bak and .acme.vault should remain right? What about the others? Which of them are mandatory?

Thanks in advance!

**Comment by ebekker** [comment]
Here is a list of what each folder is for:  https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp.Vault/Providers/LocalDiskVault.cs#L18

If you need to be able to access any of the prior assets, then you should keep all the files.  If you don't need to access past certificates and/or private keys, you can delete most of the files except the 00-* files.

The CSR files, 30, 50, 55, 56 can be deleted after you have received your certificate.  You should secure the files in 00, 40, 45.

**Comment by fpeterson194** [comment]
@ebekker thanks very much for your response buddy! Closing the issue.
