### ISSUE TITLE
reuse code

### ISSUE THREAD

**Issue by SolidCPAdmin** [ebekker/ACMESharp#229]
Hello,

We know this is open source code and reusable but we always like to ask first prior to just using someones  project with in ours.
We have a project we have been working on and would like permission to use your code in our project. solidcp.com is a mature project for web hosting and cloud hosting providers. of course we would give you full credit for the contribution.

Thanks
Rich

**Comment by ebekker** [comment]
Sounds good, you have my permission, thanks for asking.
