### ISSUE TITLE
Request: DNS-O-Matic Provider for DNS Challenge

### ISSUE THREAD

**Issue by SimonGn** [ebekker/ACMESharp#232]
You could potentially hit a lot of DNS providers at once just by going through [DNS-O-Matic](https://dnsomatic.com/) 

```
Services supported by DNS-O-Matic
Distribute your dynamic IP updates to any of the following services with a single update.
Afraid.org  
ALL-INKL.COM  
BroadbandReports.com
Line Monitoring  
ChangeIP  
City Network  
CloudFlare  
ClouDNS  
D-Link DDNS  
DNSdynamic  
DNS Exit  
DNS Made Easy  
DNS Park  
DtDNS  
DuckDNS  
DynDNS  
dyndns:free  
DynDNS Service  
DynIP  
Dynu  
EasyDNS  
eNom  
EntryDNS  
FreeDYN.de  
Google Domains  
hn.org  
Hurricane Electric  
Loopia  
Namecheap  
nic.ru  
NightOwl DDNS  
No-IP  
nsupdate.info  
ODS  
OpenDNS  
OVH  
Regfish  
SecurePoint  
SecuritySpace  
selfHOST.de  
Sitelutions  
STRATO  
XName  
WorldWideDNS  
yDNS  
yi.org  
ZoneEdit
```
(src: https://dnsomatic.com/wiki/supportedservices )

**Comment by ebekker** [comment]
Are you suggesting this for a provider to handle `DNS-01` Challenges, i.e. to provide DNS name ownership?  If so, I'm not sure how this would work, since my cursory review of the service looks like it only supports updating DNS `A` resource records with an IP address, and the ACME DNS challenge requires creating a TXT resource record.

Or am I misunderstanding your suggestion?

**Comment by SimonGn** [comment]
You understand the question correctly, and you are right, we are foiled by the limitation on record types (A & MX record only). I guess it's back to the drawing board to make a provider for each service :-) 

Anything you can do to simplify this area so that we can write our own API without much coding knowledge would be appreciated.

For me there is talk of DuckDNS supporting TXT updates so LE will work, but no idea when that's coming out. I'd guess that the API would be similar to the current DynDNS/Dys-O-Matic (and other clones) spec but they just add an extra parameter - but we'd have to wait and see.

Until then I will just buy a cheap domain to use with CloudFlare for HTTPS access until something better comes along.

**Comment by ebekker** [comment]
ACME is an API specification, and so it's naturally a programming-oriented interface.

If you can suggest something that would simplify access to the service, I can consider it.

Any 3rd-party provider that you would use to host DNS, would either require you to manage the records via an API or through a web console of some sort.  If the former, you'll need to code up something to *wire it all together*.

If the latter, then you can always use the Manual challenge handler to copy/paste the challenge response using a DNS provider's web console.  However, you have to remember that an LE-issued certificate is only good for 3 months, so you would need to repeat a manual configuration at least every 90 days.

**Comment by ebekker** [comment]
Are you an "ops" person who's comfortable with PowerShell?  If so, then the "wiring up" can be done in PowerShell relatively easily if you can figure out how to access the DNS providers API interface.

Do you have a sample DNS provider (or providers) that you're specifically concerned about?

**Comment by SimonGn** [comment]
Yeah I'm more of an Ops guy still learning how to use Powershell. I have written a few basic things, but very basic! (no more complex than a batch script). 

Ideally I would like to install a Let's Encrypt cert (with auto renew) using DNS challenge running on IIS (WS2012R2) using a non-standard port number, as ISP likes to block 443 & 80. It's for a Remote Desktop Web Gateway, so hoping to install the LE cert in other areas too.

I just figured out how to install your powershell module from the gallery (v0.8.1) and just realised that the release version doesn't seem to have CloudFlare support yet. I'm going to have to build the latest code from source if I want to use Cloudflare?? (I've never built anything from source before and honestly I'm not sure if that's within my current abilities). 

I might have to end up doing a traditional SSL cert on this one until the tools for Windows mature a bit.

**Comment by SimonGn** [comment]
Ideally I would like something in plaintext or even being able to insert a powershell script to run as part of the "Manual" verification process, with the data needed for the DNS available as JSON data or something like that.

**Comment by ebekker** [comment]
FYI, I've submitted a request to DNS-O-Matic if they would consider adding support for TXT records.  If so we can add it as a provider pretty easily.

**Comment by ebekker** [comment]
I'm going to close this ticket for now, as the original request is not possible today.  If they consider adding support for TXT, we can reopen.  If you have other requests or ideas as a tangent from this one, you can open up other tickets, thanks.

**Comment by ebekker** [comment]
Just to close the loop, here is the final response from DNS-O-Matic:
{quote}
Daniel Cheung (OpenDNS)
Aug 17, 05:59 PDT

Hello,

Thank you for getting in touch with us at OpenDNS support. We're not currently further developing the DNS-O-Matic platform other than adding new services where applicable, or fixing any issues that may arise from the current implementation.

I hope that this helps clarify things for you. At this time I will be closing the ticket by marking it as solved. However, if you have further questions, any response will automatically re-open this ticket and we would be happy to help.

Best Regards,

Daniel Cheung
Customer Support Team Lead
OpenDNS, Inc.
{quote}
