### ISSUE TITLE
New-ACMERegistration cause json cast exception

### ISSUE THREAD

**Issue by kirillta** [ebekker/ACMESharp#233]
New-ACMERegistration with `New-ACMERegistration -Contacts mailto:my.mail@hotmail.com -AcceptTos` params cause following exception, and I don't have any idea about the reason: 

> New-ACMERegistration : Unable to cast object of type 'Newtonsoft.Json.Utilities.CollectionWrapper`1[System.Collections.
Generic.KeyValuePair`2[System.String,System.String]]' to type
'System.Collections.Generic.IDictionary`2[System.String,System.String]'.
At line:1 char:1
> + New-ACMERegistration -Contacts mailto:my.mail@hotmail.com -Accep ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [New-ACMERegistration], InvalidCastException
>     + FullyQualifiedErrorId : System.InvalidCastException,ACMESharp.POSH.NewRegistration

**Comment by animetauren** [comment]
I think the error might be your Contacts Parameter, for my uses i never use the "mailto:" prefix to my email address. I know on the Wiki it shows it this way, but i just do plain and simple example@email.com and it works just fine. Try it out, and see if it works for you.

**Comment by kirillta** [comment]
It does not help, but I have run the script from another machine. Maybe this is framework differences.

**Comment by ebekker** [comment]
Can you provide some details on the configuration of the broken and working machines?  Like Win version, PS version and .NET version(s)?

**Comment by ebekker** [comment]
I'm closing this out for now, but if you provide more details, I will reopen and investigate a bit further.
