### ISSUE TITLE
Can Multiple Vaults Be Instantiated

### ISSUE THREAD

**Issue by ahaw021** [ebekker/ACMESharp#241]
Hi 

If we wanted to run this as service for clients with a dedicated server and a vault per client can this be supported?

Answered the first one: https://github.com/ebekker/ACMESharp/wiki/Vaults%2C-Vault-Providers-and-Vault-Profiles

Is there any protection such as passwords for a vault?

Is there any protection such as passwords for a vault?
Can we specify a directory for the vaults to be stored?
What is the difference between a vault and a vault profile?

![image](https://cloud.githubusercontent.com/assets/26753809/24664214/69d7499e-199d-11e7-9e20-ab279ba858ba.png)

Andrei

**Comment by ebekker** [comment]
Let me answer your questions in reverse order:
* ***What is the difference between a vault and a vault profile?***
  * A Vault is a storage location -- where the actual assets used by ACMESharp are physically stored, for example a directory on the local disk with files or some cloud storage provider with virtual file assets.
  * A Vault profile is a configuration that identifies a Vault provider and parameters to that provider.  **For example** the default, built-in Vault provider is *`local`* which is a simple file-based provider.  It supports 1 required parameter and 2 optional parameters:
    * **`RootPath`** - string path to the root directory storing the Vault instance
    * **`CreatePath`** - boolean, true to create the path if it doesn't exist
    * **`BypassEFS`** - boolean, true to disable attempt to use EFS (encrypted file system)

* ***Can we specify a directory for the vaults to be stored?***
  * Yes -- as stated in the previous question, the default Vault provider (`local`) requires a parameter **`RootPath`** to specify the path to the root directory of a Vault instance.

* ***Is there any protection such as passwords for a vault?***
  * The `local` Vault provider does not support passwords, but by default, if the vault path supports it, it tries to use EFS to encrypt the contents of the sensitive files stored in the Vault instance.  With EFS, the Windows file system will encrypt the contents of files it reads/writes using a certificated owned by the owner of the files.
