### ISSUE TITLE
Cannot install 0.8.2 via powershellgallery.com

### ISSUE THREAD

**Issue by alexhass** [ebekker/ACMESharp#242]
It is not available from this site. Can you refresh, please?

**Comment by nebffa** [comment]
This would be awesome to have please!

**Comment by rayholtz** [comment]
I'd like to get 0.8.2 installed too.  It seems that 0.8.1 doesn't have the 'install to IIS' cmdlet.

**Comment by ebekker** [comment]
WIP...

**Comment by yamlfd** [comment]
Completed?

**Comment by ebekker** [comment]
Nope, I'm still working on it -- you can install *early access* releases from the MyGet feed which you can find [here](https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Downloads:-PowerShell-Modules).  But there are some breaking changes with installation coming in the next release so I'm working getting ahead of it by adding and updating documentation.

**Comment by alexhass** [comment]
Issue seems to be fixed. At least I installed a 0.9.1 or something like this.
