### ISSUE TITLE
IIS Handler's web.config results in HTTP error 500 due to locked handlers

### ISSUE THREAD

**Issue by gbeekmans** [ebekker/ACMESharp#243]
I'm testing ACMESharp 0.8.2 on a Windows 2012 machine.

When I run **Complete-ACMEChallenge** it creates a web.config file with the following contents:
```
<?xml version="1.0" encoding="UTF-8"?>
 <configuration>
     <system.webServer>	     
         <staticContent>
             <mimeMap fileExtension="." mimeType="text/json" />
         </staticContent>
         <handlers>
             <clear />
             <add name="StaticFile" path="*" verb="*" type=""
                     modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule"
                     scriptProcessor="" resourceType="Either" requireAccess="Read"
                     allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
         </handlers>
     </system.webServer>
 </configuration>
```

This ends up causing an HTTP 500 error due to the use of the <handlers> tag. On my vanilla installation of IIS the handlers are locked and trying to specify them in web.config results in the error.

A way to fix this is by running the following command:

`c:\windows\system32\inetsrv\appcmd.exe unlock config -section:system.webServer/handlers`

There might be a better way of accomplishing this (perhaps this can be done for just the site in question versus system wide).

I have added that command to run before **Complete-ACMEChallenge** to ensure it's always set before trying to subsequently submit the challenge.

On my system, I can even omit the entire `<handlers>` section and things still work correctly though this probably have an issue on production systems that don't have an out-of-the-box configuration.

**Comment by emilbayes** [comment]
I second this. Had the same issue yesterday on a vanilla Windows Server 2016 with IIS just installed. Ended up just removing the web.config before calling `Submit-ACMEChallenge`

**Comment by ebekker** [comment]
Yes, unfortunately, the generated `web.config` file above was crafted as a *best effort* to accomodate most situations based on past input and experience.  In your cases, there is an inherited policy that is in conflict with the settings of the web.config file.  We could remove the `<clear/>` tag, but then it would fail for many other users where their inherited policies are actually overriding the handling of the `.well-known/*` files.

Unfortunately, this is a case where one config doesn't satisfy everyone's situations.

If there is a way to *scope* the configuration to the single site that would not conflict with the policy, I'll be happy to make the change.

**Comment by craige1** [comment]
It seems that on Server 2016, the default iis install is to have the handlers locked. 
Maybe this info should be front and centre on the quickstart guide, as i expect many people to run into this.

**Comment by ebekker** [comment]
@craige1 -- that's a great idea, would like to contribute to the docs?  The ACMESharp docs are now all hosted [here](https://pkisharp.github.io/ACMESharp-docs/) and you can contribute to the GitHub repo directly.  If you (or anyone else) is interested in contributing, I would be happy to discuss further.

**Comment by tosiara** [comment]
Just came across this issue and the provided command resolved it. Thanks

**Comment by SiloReed** [comment]
Is there a way to problematically  discover the URI of the local host after Complete-ACMEChallenge executes? That way you could have a script that executes something like: 
$response = Invoke-WebRequest -Uri 'http://localhost/.well-known/acme-challenge/_hnxWNLAFXqwasRe46Fl1Q8K_pl5_ZJfqF8CVRCSbyQ' 
and then executes 
c:\windows\system32\inetsrv\appcmd.exe unlock config -section:system.webServer/handlers
if 500 error is returned.

**Comment by wvdweerd** [comment]
I encountered another problem with the generated web.config:
`<staticContent>
             <mimeMap fileExtension="." mimeType="text/json" />
         </staticContent>`

If there is already a mimeMap for "." (possibly with a different type like "text/plain", then redefining it will result in an error.

Better is to include first a `<remove fileExtension="." />`. so this part of the web.config looks like:

` <configuration>
     <system.webServer>	     
         <staticContent>
             <remove fileExtension="." />
             <mimeMap fileExtension="." mimeType="text/json" />
         </staticContent>
         <handlers>`
