### ISSUE TITLE
Complete-ACMEChallenge : the given identifier was not found in the registry

### ISSUE THREAD

**Issue by jcasale** [ebekker/ACMESharp#245]
Using the [ACMESharp.0.8.2.293](https://www.myget.org/feed/acmesharp-posh-staging/package/nuget/ACMESharp) package which appears to contain the IIS handler I am after, I encounter the following error:

    New-ACMEIdentifier -Dns <my-fqdn> -Alias <my-alias> -ErrorAction Stop
    Complete-ACMEChallenge 'my-alias' -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = 'Default Web Site' }
    Complete-ACMEChallenge : the given identifier was not found in the registry
    At line:1 char:1
    + Complete-ACMEChallenge -IdentifierRef <my-fqdn> -ChallengeType http- ...
    + ~~~~...
        + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], KeyNotFoundException
        + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,ACMESharp.POSH.CompleteChallenge

Without opening this up in vs (which is not convenient in this env), does anyone have a guess as to what this relates to? A missing provider (the IIS provider appears to be present) or a failure to parse the vault for the identifier just created?

**Comment by ebekker** [comment]
Does the "Default Web Site" exist on this server in IIS?

**Comment by jcasale** [comment]
Yes it does.
```
C:\Windows\System32\inetsrv>appcmd list site
SITE "Default Web Site" (id:1,bindings:http/*:80:,net.tcp/808:*,net.msmq/localhost,msmq.formatname/localhost,net.pipe/*,https/:443:,http/127.0.0.1:80:,https/127.0.0.1:443:,state:Started)
SITE "Exchange Back End" (id:2,bindings:http/*:81:,https/*:444:,net.pipe/*,state:Started)
```

**Comment by ebekker** [comment]
In your code example, you have:
```PowerShell
New-ACMEIdentifier -Dns <my-fqdn> -Alias <my-alias> -ErrorAction Stop
Complete-ACMEChallenge 'my-alias' -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = 'Default Web Site' }
```

In the first line, you use `<my-alias>` and in the second you use `'my-alias'` -- now I'm guessing these are place holders, but whatever those values are, you need to make sure they match.

Also, make user that you have Handler Profile defined for `iis`

**Comment by DavidDeSloovere** [comment]
I'm also getting the **Complete-ACMEChallenge : the given identifier was not found in the registry** error.
Running `Get-ACMEChallengeHandlerProfile -ListChallengeHandlers` only returns **manual**.
Any clues to what I can do here?



```

PS C:\ProgramData\ACMESharp\sysVault>     New-AcmeIdentifier -Dns $domain -Alias $alias

IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : test.REDACTED.REDACTED.REDACTED.com
Uri            : https://acme-v01.api.letsencrypt.org/acme/authz/REDACTED
Status         : pending
Expires        : 17/08/2017 8:00:33
Challenges     : {, , }
Combinations   : {0, 1, 2}


PS C:\ProgramData\ACMESharp\sysVault> Complete-ACMEChallenge $alias -ChallengeType http-01 -Handler iis -HandlerParameters @{WebSiteRef="$iissitename"}

Complete-ACMEChallenge : the given identifier was not found in the registry
At line:1 char:1
+ Complete-ACMEChallenge $alias -ChallengeType http-01 -Handler iis -Ha ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,ACMESharp.POSH.CompleteChallenge
```

**Comment by JozoSlejko** [comment]
I'm having the same situation as DavidDeSloovere.

**Comment by EdgarTorresNYC** [comment]
I'm having the same issue:

```
PS P:\> Complete-ACMEChallenge $alias -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = 'Default Web Site' }

Complete-ACMEChallenge : the given identifier was not found in the registry . . .
```

After a couple days of research (and stumbling upon other, older @ebekker  posts), I was able to determine that, like others, I am missing the **iis** challenge handler:

```
PS P:\> Get-ACMEChallengeHandlerProfile -ListChallengeHandlers
manual
```

I also noticed that I was missing the **ACMESharp.Providers.IIS.dll** and **ACMESharp.Providers.IIS.pdb** files packaged in the original 0.8.1 .zip; however, I _did_ find an **ACMESharp.Providers.IIS.psd1** file (as well as an **ACMESharp-IIS** folder with respective **.psd1** and **.psm1** files).  I suspected that I didn't need the missing files, since the other files and folder are there, but I still copied the missing files from the 0.8.1 .zip file into the ACMESharp modules folder.  As expected, adding the missing files didn't help.  I tried removing and re-importing the ACMESharp module, but still no luck.

I'm running ACMESharp 0.8.5.313 on Windows Server 2016 (1703 July build).  The _system.webServer_ contents of my **acme-challenge** folder's **web.config** file follow:

```
<system.webServer>
	<validation validateIntegratedModeConfiguration="false" />
	<staticContent>
		<remove fileExtension="." />
		<mimeMap fileExtension="." mimeType="text/json" />
	</staticContent>

	<handlers>
		<clear />
		<add name="StaticFile" path="*" verb="*" type=""
			modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule"
			scriptProcessor="" resourceType="Either" requireAccess="Read"
			allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
	</handlers>
</system.webServer>
```

If I execute the `Complete-ACMEChallenge` request with the **manual** handler for the **http-01** challenge type,  I don't get the error at the top of this post, which is expected, since the **manual** handler is registered:

```
PS P:\> Complete-ACMEChallenge $alias2 -ChallengeType http-01 -Handler manual -HandlerParameters @{ WriteOutPath = "$acmelog" }`

. . .
== Manual Challenge Handler - HTTP ==
  * Handle Time:      [8/11/2017 10:09:45 AM]
  * Challenge Token:  [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
To complete this Challenge please create a new file
under the server that is responding to the hostname
and path given with the following characteristics:
  * HTTP URL:     [http://site2.domain.com/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
  * File Path:    [.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
  * File Content: [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
  * MIME Type:    [text/plain]
------------------------------------
```

At this point, I can then follow the manual instructions and successfully continue with the rest of the challenge and certificate processes.

Any ideas on how I can register the **iis** handler for the **http-01** challenge?  Is it a bug with the current version of the ACMEShapr POSH module?  Any and all help would be much appreciated!

**Comment by ebekker** [comment]
Sorry guys -- I accidentally promoted the *pre-release* version of ACMESharp PS module to the gallery too early.  You're now using the next version of the module and I didn't want to release it before the new docs were ready, but unfortunately too late to pull back now.

You can either uninstall and reinstall the ACMESharp module (using psget cmdlets) to an [older release](https://www.powershellgallery.com/packages/ACMESharp/0.8.1) or you can try out the new documentation which is not 100% complete yet:
* [(WIP) Module Downloads](https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Downloads:-PowerShell-Modules)
* [(WIP) Module Install](https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Installation:-ACMESharp-PowerShell-client)
* [(WIP) New Quick Start](https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Quick-Start)

**Comment by DavidDeSloovere** [comment]
@ebekker No worries. You are doing all the hard work, we just complain that it's not working ;-)

List installed modules `Get-Module –ListAvailable`
Remove module `Uninstall-Module ACMESharp`
Install stable `Install-Module -Name ACMESharp -RequiredVersion 0.8.1`

And now... 🎉 

```
PS C:\Users\david.desloovere> import-module acmesharp
PS C:\Users\david.desloovere> Get-ACMEChallengeHandlerProfile -ListChallengeHandlers
manual
awsRoute53
awsS3
iis
PS C:\Users\david.desloovere>
```

For those who want to try the prelease, as you can see Downloads: PowerShell Modules page, they are on myget.

**Comment by MatthewALHardy** [comment]
Thanks Eugene and David. Uninstalling the pre-release and installing 0.8.1 worked for me.
Small note - I needed to use
`Install-Module -Name ACMESharp -RequiredVersion 0.8.1 -AllowClobber`
As there was already a cmdlet called Get-Certificate on my Windows 2016 Powershell 5.1  server
https://technet.microsoft.com/library/6da3eebc-7b3f-4130-b266-9b2ad6df4318(v=wps.630).aspx
```
PS C:\Windows\system32> Install-Module -Name ACMESharp -RequiredVersion 0.8.1
PackageManagement\Install-Package : A command with name 'Get-Certificate' is already available on this system. This module 
'ACMESharp' may override the existing commands. If you still want to install this module 'ACMESharp', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.C 
   mdlets.InstallPackage
```

**Comment by EdgarTorresNYC** [comment]
Thanks, guys! I also had to use the `-AllowClobber` parameter, in order to install the older ACMESharp module on my Windows Server 2016 server, but at least I got it installed.

**Comment by mw42** [comment]
Thanks so much, working for me, too.

I installed version 0.8.1 but it gave an error when I tried "-AllowClobber". Without it everthing is working.

One last thing: if you want to remove the installed version of ACME you might have to close all the Powershells. Otherwise you might get "still in use" error

**Comment by ebekker** [comment]
Thanks everyone for the confirmations and feedback.  It looks like mostly everyone's situation has been remedied for now (except @jcasale ?).  I'm going to close this issue for now.

The upcoming changes included much improved and expanded documentation which will address the proper steps moving forward with the new release.  It also discussed the `-AllowClobber` flag and when and why you need to specify it (hint, it's a bug in the PowerShellGet module).

**Comment by NTServices** [comment]
I've on a Win 2012 R2 withe the PS ver 5.0.10586.117 the issue that the IIS Extension Module can be imported but 
Get-ACMEChallengeHandlerProfile -ListChallengeHandlers shows only
manual
Get-ACMEInstallerProfile -ListInstallers shows 
nothing
so it's no surprise that e.g.
Complete-ACMEChallenge dns1 -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = 'Default Web Site' }
shows 
Complete-ACMEChallenge : the given identifier was not found in the registry

by the way the Install-Module ACMESharp -AllowClobber 
shows the error: There is no such a parameter

**Comment by JohnLBevan** [comment]
@NTServices  after installing and enabling the IIS Provider (see [WIP Quick Start](https://github.com/ebekker/ACMESharp/wiki/%5BWIP%5D-Quick-Start#step-1-install-acmesharp)) you may need to restart your PowerShell session.  Once restarted you should see `iis` appear under both of the commands listed.
