### ISSUE TITLE
Certificate not verified (Intermediate Certificates/root) and Android browser problem?

### ISSUE THREAD

**Issue by Rolf1967** [ebekker/ACMESharp#248]
**I’ve have created 3 certificate files with Acmesharp:**

trimsalonbunny.nl.crt    > it’s coded with Let’s Encrypt1#0!ULet’s Encrypt Authority X30
trimsalonbunny.nl.pem > —-BEGIN RSA PRIVATE KEY—–
trimsalonbunny.nl.pfx   > also coded, cann't read it

**I've add this to my Apache 2.2 sni.conf:**

SSLCertificateFile      “trimsalonbunny.nl**.crt**”
SSLCertificateKeyFile “trimsalonbunny.nl**.pem**”

**In my Apache logfile I have this problem:**
[warn] RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)

When I visit with **Google Chrome** on my Android phone   https://trimsalonbunny.nl    then I see a **warning** about the certificate

Can you, please, help me to solve this problem....

Best regards,
Rolf

**Comment by WallyRanson** [comment]
I have no problem here on either on my android phones, Moto X Style and Samsung Galaxy S5, both with Android 6.0.1.
I tried both the Chrome and Firefox browsers in both mobile and desktop mode.
Seems like the issue is on your phone.
Is it the newest browser version?

**Comment by Rolf1967** [comment]
Yes, the problem has been solved.

I've added all the LetsEncrypt certificates to my Windows Certificates > trusted certificates
https://letsencrypt.org/certificates/

In my Apache 2.2 sni.conf I 've added:
SSLEngine on
SSLProtocol             ALL -SSLv2 -SSLv3 +TLSv1 +TLSv1.1 +TLSv1.2
SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
SSLHonorCipherOrder     on
SSLCertificateFile "path to trimsalonbunny.nl.crt"
SSLCertificateKeyFile "path to trimsalonbunny.nl.pem"
SSLCertificateChainFile	"path to lets-encrypt-x3-cross-signed.pem"
# Guarantee HTTPS for 1 Year including Sub Domains
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
BrowserMatch ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
SSLStrictSNIVHostCheck off

Problem solved....
