### ISSUE TITLE
awsRoute53 challenge configuration

### ISSUE THREAD

**Issue by dellock6** [ebekker/ACMESharp#250]
Hi,
I've searched through all the pages I found around, but it's either me or the docs, I can't find any place that explains how I am supposed to use the awsRoute53 challenge provider. I understood I have a list of parameters I have to pass the the challenge, and I grabbed them already, but "where" do I store those parameters? In a text file (and if so, where I save it), as a variable for the complete-acmechallenge command, else?

Also, what are the minimum permissions that we need so I can create a proper IAM profile in aws?

Thanks,
Luca

**Comment by ebekker** [comment]
As far as the permissions, here is the list of operations that are performed against AWS R53 to implement this:
* ListResourceRecordSets
* ChangeResourceRecordSets

**Comment by ebekker** [comment]
To find the parameters that the `AwsRoute53` provider supports, you issue the following PowerShell:

```PowerShell
PS> Get-ACMEChallengeHandlerProfile -GetChallengeHandler awsRoute53 -ParametersOnly | Out-GridView
```

This is based on [this wiki page](https://github.com/ebekker/ACMESharp/wiki/Challenge-Types%2C-Challenge-Handlers-and-Providers).

**Comment by ebekker** [comment]
Specifically, for the `aws-route53` challenge handler provider, the parameters are:
* **`HostedZoneId`** - required
* **`ResourceRecordType`** - optional, defaults to TXT
* **`ResourceRecordTtl`** - optional, defaults to 300s

Additionally, all AWS providers support the following for different combinations of supported authentication based on the calling context (i.e. inside AWS, specify a profile, specify creds, etc.):
* **`ACCESS_KEY_ID`**
* **`SECRET_ACCESS_KEY`**
* **`SESSION_TOKEN`**
* **`PROFILE_NAME`**
* **`PROFILE_LOCATION`**
* **`IAM_ROLE`**
* **`REGION`**
