### ISSUE TITLE
New-ACMECertificate fails to find registered alias.

### ISSUE THREAD

**Issue by dschuermans** [ebekker/ACMESharp#253]
Hello,

I've created my self a powershell script which reads a list of domains from a text file, per domain generates an alias using the current timestamp and the proceeds to perform the following for each domain:

1.) New-ACMEIdentifier -Dns $Domain -Alias $Alias
2.) Complete-ACMEChallenge $Alias -ChallengeType dns-01 -Handler manual
3.) Use the GoDaddy API to create the requested TXT record with the specified value as requested in the challenge response
4.) Submit-ACMEChallenge $Alias -ChallengeType dns-01
5.) Check for the validity of the identifier in 10 second intervals using Update-ACMEIdentifier $Alias -ChallengeType dns-01
6.) New-ACMECertificate $Domain -Generate -Alias $Alias
7.) Submit-ACMECertificate $Alias
8.) Check for certificate serial number in 10 second intervals using (Update-ACMECertificate $Alias).SerialNumber
9.) Export the certificate as PFX using Get-ACMECertificate $Alias -ExportPkcs12 "$($OutputFolder)\$($Alias).pfx"

The weird things is that for my first listed domain in my text file, imap.schuermans.me it will work correctly.
However, as soon as the script gets to the next domain, it eventually errors out on 6.) with the following message:

VERBOSE: Generating new certificate for domain smtp.schuermans.me with alias smtp.schuermans.me_201705240931
New-ACMECertificate : The given key was not present in the dictionary.

As you can see, i'm always using the same $Domain and $Alias variables and they are not changed in between to something else.

When checking the available identifiers in my vault using Get-ACMEIdentifier, there is an identifier for the shown alias:

Seq    : 30
Id     : c005df79-1ee6-4b19-93d7-bd7923a71e3f
Alias  : smtp.schuermans.me_201705240931
Label  :
Dns    : smtp.schuermans.me
Status : valid

Any ideas on what i can try to do?

**Comment by dschuermans** [comment]
Found it, 6.) should be New-ACMECertificate $Alias -Generate -Alias $Alias

**Comment by ebekker** [comment]
Ah yes, you are using the same alias name (`$Alias`) for both the Identifier and the Certificate.
