### ISSUE TITLE
authorizations for these names not found or expired

### ISSUE THREAD

**Issue by bitsfarm** [ebekker/ACMESharp#258]
Hi,

I'm getting a error as detailed below,  is this possibly relating to using an Ngrok sub-domain or is it a code inconsistency?

Thanks
Jamie.

`System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> ACMESharp.AcmeClient+AcmeWebException: Unexpected error +Response from server:`
+ Code: Forbidden
+ Content: {
 "type": "urn:acme:error:unauthorized",
 "detail": "Error creating new cert :: authorizations for these names not found or expired: 17e5f37e.ngrok.io",
 "status": 403
} ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
  at System.Net.HttpWebRequest.GetResponse()
  at ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:line 700
  --- End of inner exception stack trace ---`

**Comment by WallyRanson** [comment]
Check that you can access port 80 on your host (17e5f37e.ngrok.io)

**Comment by bitsfarm** [comment]
Yes it was accessible, connections are shown via Ngrok console.
GET /.well-known/acme-challenge/z2657P6niQbofHs2wnZoZo8oiGa9VAcywiepXaW4DLk 200 OK

I am seeing code progress past the handle method in this instance, this is based on code marked deprecated, however it is methods I have seen functioning correctly in examples.
```

var chAns = client.GenerateAuthorizeChallengeAnswer(authState, chType);
authState.Challenges = new List<AuthorizeChallenge> { chAns };
client.SubmitAuthorizeChallengeAnswer(authState, chType);

 while (authState.Status == "pending")
                    {
                        Thread.Sleep(4000);
                        var newAuthState = client.RefreshIdentifierAuthorization(authState);
                        if (newAuthState.Status != "pending")
                        {
                            authState = newAuthState;
                        }
                    }
```

The above is the code marked deprecated, I have tried the other newer methods for carrying out the job but I seem to start needing dependencies for Microsoft.Sharepoint.Client + more ... so with time being an issue i've been sticking to my original direction.

From here I am creating my CSR and calling RequestCertificate:

```
var cp = CertificateProvider.GetProvider();
var rsaKeys = cp.GeneratePrivateKey(rsaPkp);
            var csrDetails = new CsrDetails
            {
                CommonName = domain,
            };            
var rsaPkp = new RsaPrivateKeyParams(); 
var csrParams = new CsrParams
            {
                Details = csrDetails,
            };
var csr = cp.GenerateCsr(csrParams, rsaKeys, Crt.MessageDigest.SHA256);
byte[] derRaw;
            using (var bs = new MemoryStream())
            {
                cp.ExportCsr(csr, EncodingFormat.DER, bs);
                derRaw = bs.ToArray();
            }
            var derB64U = JwsHelper.Base64UrlEncode(derRaw);
            var certRequ = client.RequestCertificate(derB64U);


```
It is at this point it decides to throw the previous error.

Any ideas what could be causing the inconsistency?

**Comment by WallyRanson** [comment]
Ok, I am not so much into the code part of this, but what are your csrDetails?
There have been funny errors, if details where added, that was not supported by Lets Encrypt.

**Comment by bitsfarm** [comment]
I've experimented with a few of the csr fields, but currently it should only be common name.  Although i have seen OpenSSL using a defaults file and it may be including email and few other fields however debugger indicated they were null. The file is included in the acmesharp source but I'm away from my desk at moment so tricky to find

I've included the code in the start of second section above for csr

Thanks

**Comment by WallyRanson** [comment]
Sounds ok then.
THere have earlier been issues with this, because OpenSSL support alot, but Let's Encrypt do not. Only the fields that Lets Encrypt can validate is supported and those are quite few.
I do not know what causes the error then. :(

**Comment by bitsfarm** [comment]
Thanks for the assistance,  I've managed to progress it further now and seems it was a fault with obsolete code and other abstract issues with the platform getting in the way.

**Comment by ericwj** [comment]
I am getting this because port  80 was not accessible, but I get stuck after opening the port.
Trying to Submit-AcmeCertificate, I get "asset file already exists" which seems like #130.
How to proceed?

**Comment by ebekker** [comment]
@bitsfarm -- if you have any additional insight into what the issue was, or what *usability* issues you have with the platform abstractions, please do share.  It may be helpful for others with similar problems, and it would be great feedback that can be incorporated into the tools for future improvements.
