### ISSUE TITLE
New-ACMECertificate: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by AchdukeNavaron** [ebekker/ACMESharp#268]
Hi, 

I do have a weired problem.
I am trying to issue a multiname certificate.

If I do this:
New-ACMECertificate "$Domain_1" -Generate -AlternativeIdentifierRefs ([array]$($Aliases -join',';)) -Alias $CertificateName

I get this error:
New-ACMECertificate: The given key was not present in the dictionary

Original:
New-ACMECertificate : Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
In C:\Zertifikate\Test_FirstUse.ps1:137 Zeichen:1
+ New-ACMECertificate "$Domain_1" -Generate -AlternativeIdentifierRefs  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMECertificate], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,ACMESharp.POSH.NewCertificate

The Array is defiened with:
$Aliases += "'$Domain_2'"
$Aliases += "'$Domain_3'"

If I would just pass them with -AlternativeIdentifierRefs $Aliases, there would be breaks after each Alias. That's the reason why I define them with ([array]$($Aliases -join',';)). The output of this would be:
'test2.company.at','test3.company.at'
which would be the correct output for being converted into an array again (In on line)

If I enter those FQDNs manually, it works fine...

**Comment by WallyRanson** [comment]
Did you define $Aliases as a array in the before using it?

If you did not define it then I think it defaults to a string and the $Aliases += will then just concatenate on the string.
Try to single step your script and then after do a $Aliases in the console to see what it contains.
My guess is it contain something like
`www.domain1.comwww.domain2.com`
When you do the ([array]$($Aliases -join',';)), then you just convert one long string into an array with one element, ie. www.domain1.comwww.domain2.com

If you define the array before its used with
`$Aliases=@()`
Then your $Aliases+= will add to an array instead and the result when do a $Aliases in the console in a single stepping should show something like
```
www.domain1.com
www.domain2.com
```
And this format should be able to be used directly in as the AlternativeIdentifierRefs parameter.

**Comment by ebekker** [comment]
This syntax:
```powershell
([array]$($Aliases -join',';))
```
will produce a single element array whose content is a string with all the different values in `$Aliases` concatenated, which is pby not what you want.  If `$Alias` is already an array, then you can force the cast using `([array]$Alias)`.  If `$Alias` is just a single element and you want to force it to be treated as an array, use `@($Alias)`.
