### ISSUE TITLE
Staging Environment support

### ISSUE THREAD

**Issue by kirillkovalenko** [ebekker/ACMESharp#275]
Is there a way to use [Let's Encrypt Staging Environment](https://letsencrypt.org/docs/staging-environment/) with ACMESharp?

**Comment by ebekker** [comment]
When you initialize your Vault, you can optionally specify a `BaseService` or `BaseUri` which defines the URL endpoint that all operations will be performed against when using ACMESharp with that Vault.

`BaseService` defines a couple of *well-known* ACME servers, specifically Let's Encrypt PROD and STAGE, whereas `BaseUri` is used to let you specify some arbitrary ACME server endpoint, for example if you run your own server in your own environment.

So the short answer is, when you initialize your Vault, simply specify the `-BaseService LetsEncrypt-STAGING` parameter, for example:

```powershell
Initialize-ACMEVault -BaseService LetsEncrypt-STAGING
```

**Comment by kirillkovalenko** [comment]
Thank you!
