### ISSUE TITLE
Request payload did not parse as JSON

### ISSUE THREAD

**Issue by WouterTinus** [ebekker/ACMESharp#279]
Hi everyone,

We are using the latest stable release of ACMESharp for letsencrypt-win-simple but we've run into the following error message upon calling the function SubmitChallengeAnswer.

{
  "type": "urn:acme:error:malformed",
  "detail": "Request payload did not parse as JSON",
  "status": 400
}

What the Fiddler trace shows went over the line looks like perfectly fine JSON to me though. I hope someone might be able to help.

https://github.com/Lone-Coder/letsencrypt-win-simple/issues/508

**Comment by ebekker** [comment]
I've posted comments in the original ticket

**Comment by ebekker** [comment]
The original issue in the original ticket has been addressed.
