### ISSUE TITLE
v. 0.9.0.316 Get-ACMECertificate -ExportPkcs12 - pfx file ends up with wrong password set

### ISSUE THREAD

**Issue by LubomirH** [ebekker/ACMESharp#282]
Hi, 
When I run the commands bellow, the certificate is exported OK.
It is however not possible to import the resulting pfx file, I keep getting an error that the password is wrong.
It worked 3 months ago, when I used it last time. At that time with version 0.8.1.

```powershell
PS C:\Windows\system32> $mypwd = ConvertTo-SecureString -String '12345' -Force –AsPlainText
PS C:\Windows\system32> Get-ACMECertificate GalleryCert1 -ExportPkcs12 "D:\@\Let'sEncrypt\GalleryCert111111.pfx" -CertificatePassword $mypwd
```

**Comment by ebekker** [comment]
Not sure you were doing the same thing 3 months ago if it was working -- `Get-ACMECertificate` takes a `string` for the `-CertificatePassword` parameter.

In your case, you're passing it a SecureString instance, which the PowerShell CLI is trying it's best to convert to a string, which in this case it's just simply doing `.ToString()` on the object so your password is being passed in as the literal string value *`System.Security.SecureString`*.

**Comment by LubomirH** [comment]
You might be right, I am getting old :)
I guess I have tried to do it the built-in Export-PfxCertificate command way, which seemed to me more secure, but might have in the end use just a simple string and just forgot to document it properly.

I don't really understand the benefit of the ConvertTo-SecureString so I will not try to persuade you that you should make it possible to use also with your command, so I guess you can close this issue.

So sorry for false alarm and thanks a lot for your great work ;)

**Comment by ebekker** [comment]
Actually, I originally intended to support (require, actually) that `SecureString` would be used as input for any sensitive cmdlet parameters in the POSH module, but then there was an indication that [it would be deprecated and removed](https://github.com/dotnet/corefx/issues/1387#issuecomment-126092613) from .NET altogether.  This was back when ACMESharp was still in its infancy.

Today the story is a little different and SecureString will be fully supported in .NET going forward (only it may not preserve all of its security properties equally across all supported platforms).

However, over time and feedback from ACMESharp users, I have found that most likely not all users would want to be forced to use SecureString even if it is the more secure approach, so at this point I'm glad I didn't introduce it as a requirement.

Going forward, I will pby introduce the use of SecureString as an optional feature, for example, using it for sensitive parameters if it is provided, and if a string is provided instead, silently convert it for the user.  There was even preliminary support for it introduced into the Extension mechanism for [Provider Parameters](https://github.com/ebekker/ACMESharp/blob/52f66df3768781116b5dfecba4c17a6f81d48ca1/ACMESharp/ACMESharp/Ext/ParameterDetail.cs#L62) which I will likely resurrect and complete.
