### ISSUE TITLE
ACMESharp 0.9.0.321' is not compatible with constraint: ACMESharp (>= 8.2.0)

### ISSUE THREAD

**Issue by Jasin2069** [ebekker/ACMESharp#289]
Trying to install the Cloudflare in package manager. 

ACMESharp 0.9.0.321' is not compatible with 'ACMESharp.Providers.CloudFlare 0.9.0.321 constraint: ACMESharp (>= 8.2.0)

The version check should be >= 0.8.2.0
Seems to be the case for all of the extension providers.

**Comment by ebekker** [comment]
That's very peculiar -- I just checked the entry for CloudFlare (as well as other extension providers) on the PowerShell Gallery and even on the site it shows the dependency as `ACMESharp (>=0.8.2)`:
* https://www.powershellgallery.com/packages/ACMESharp.Providers.CloudFlare
* https://www.powershellgallery.com/packages/ACMESharp.Providers.IIS
* https://www.powershellgallery.com/packages/ACMESharp.Providers.Windows

Same thing for the pre-release feed on MyGet.

**Comment by ebekker** [comment]
@Jasin2069  and @samcic -- what version of PowerShell are you using and what OS?

**Comment by samcic** [comment]
@ebekker In my case I'm just trying to install the NuGet package ACMESharp on a fresh project to test things out. Fails with error below. I was going to log an issue, but then found this one which looked like it was more or less the same issue.

Environment:
* Windows 10 Enterprise x64
* Visual Studio Enterprise 2017 15.3.4

Reproduction steps (in Visual Studio):
* New Project => Console Application (.NET Framework 4.7)
* Manage NuGet Packages => Include Prerelease => Install ACMESharp v 0.8.5.313

Result Error Message: 

Unable to resolve dependencies. 'ACMESharp.PKI.Providers.OpenSslLib32 0.7.0' is not compatible with 'ACMESharp 0.8.5.313 constraint: ACMESharp.PKI.Providers.OpenSslLib32 (>= 0.8.5.313)'

Are you able to repro this?

**Comment by ebekker** [comment]
Doh!  I *assumed* you were talking about the PowerShell modules, just realized you were talking about the nuget packages, and the pre-release ones off of MyGet to boot.  I verified the feed does show a [dependency](https://www.myget.org/feed/acmesharp/package/nuget/ACMESharp.Providers.CloudFlare#dependencies) of `8.2.0` for CloudFlare as well as the other providers.  I must have accidentally truncated the leading `0.` in the version.

I'll correct this shortly and re-publish...

**Comment by ebekker** [comment]
This issue should be fixed with the latest CI build and publish to the pre-release feed.

I'll be pushing these out to nuget.org shortly as well.

**Comment by samcic** [comment]
Confirm fixed for my previous reproduction steps, nice work! From my side this is ok to close now.
