### ISSUE TITLE
LE ACME-Exchange.ps1 Exchange 2016 Renewal issues (part 2)

### ISSUE THREAD

**Issue by angelperezleon** [ebekker/ACMESharp#294]
Hi Eugene,

Can you advise on the following topic https://community.letsencrypt.org/t/le-acme-exchange-ps1-exchange-2016-renewal-issues-part-2/42543

I am using the ACME-Exchange.ps1 to renew my exchange cert which has already been in place for 2-months now and time has come to renew.

Advise greatly appreciated.

thanks

**Comment by angelperezleon** [comment]
An update to ACME-Exchange module would be great!

**Comment by ebekker** [comment]
In the script, he's using a fixed alias for the DNS Identifier and (presumably for the certificate) on every invocation, so the first time you run it, it will work, but the second and subsequent times will fail because an alias can only be assigned once.  I would recommend generating an alias that is time-sensitive, for example, maybe append the name with the current Year and Month, then it won't conflict from run to run as long as sufficient time has passed (at least 1 month).

**Comment by ebekker** [comment]
I'm afraid I'm not in a position to "take over" management of the ACME-Exchange script, for one I don't have access to an Exchange setup, I'm also time constrained.  Perhaps you can reach out to NetoMeter [directly](https://www.netometer.com/aboutus.php) to ask for some assistance with their script/screen cast?

**Comment by angelperezleon** [comment]
@ebekker 
Appreciate the advise, now I understand that the ACME-Exchange is different branch of ACME script that is managed elsewhere (netometer) I thought you where all the same entity.

I have been using date time stamps in the process of generating unique timestamps, but I think I am getting a conflict elsewhere..

This ticket can be closed, thanks very much.

**Comment by alvesman** [comment]
Maybe this script can solve your problem:
[https://vanbrenk.blogspot.pt/2017/09/new-version-of-exchange-certificate.html](https://vanbrenk.blogspot.pt/2017/09/new-version-of-exchange-certificate.html)

**Comment by angelperezleon** [comment]
@alvesman 
Tried the script and works well, thanks, but i noticed the autorenewal task is been performed every day.  Would be worth changing this to 60-days.

**Comment by alvesman** [comment]
You just have to open Task Manager, look for the task "_Let's Encrypt certificaterenewal - www.FrankysWeb.de_" and change the trigger section.

**Comment by angelperezleon** [comment]
OK, I know, just pointing this out in case this is something you can add to script to.
Its worth leaving it to run the next day to make sure auto-renewal processes works through task scheduler.
