### ISSUE TITLE
Error creating San Certificate

### ISSUE THREAD

**Issue by frapps** [ebekker/ACMESharp#296]
Hi, I am trying to create a san certificate with 100 names in it. This is apparently the limit of lets encrypt. 

My code is this. 

New-ACMECertificate san0 -Generate -AlternativeIdentifierRefs san1,san2,san3... san99 -Alias empSanCertFinal

When I submit the certificate I get the following error. 

S C:\Users\Administrator> Submit-ACMECertificate empSanCertFinal
ubmit-ACMECertificate : Error creating new cert
t line:1 char:1
 Submit-ACMECertificate empSanCertFinal
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : OperationStopped: (ACMESharp.Vault.Model.CertificateInfo:CertificateInfo) [Submit-ACMECe
  rtificate], AcmeWebException
   + FullyQualifiedErrorId : urn:acme:error:serverInternal (500),ACMESharp.POSH.SubmitCertificate

My code works fine if I just do like 3 san names. How could I find out more information about the actual error?

**Comment by cpu** [comment]
Hi @frapps,

We are having some latency problems that are preventing some 100 SAN certificates from being issued. [See this thread/reply for more information](https://community.letsencrypt.org/t/certificate-error-with-large-san-cert/42953/4).

I recommend you subscribe there and follow the workaround suggested for the meantime (reducing the # of SAN entries on the certificate).

Apologies for the inconvenience.

(ACMESharp mods: I believe you can close this issue - it is a problem with Boulder/Let's Encrypt not ACMESharp).

**Comment by frapps** [comment]
Great. Thank you.

**Comment by ebekker** [comment]
@cpu -- thanks for the heads up.

Love your dog, btw.
