### ISSUE TITLE
What is wrong???  Can't submit certificate.

### ISSUE THREAD

**Issue by meluvalli** [ebekker/ACMESharp#305]
Can't submit certificate because it's already submited. 

But can't update certificate because it's not submited.

PS C:\Users\Administrator> Submit-ACMECertificate test.mydomain.com-20171025
Submit-ACMECertificate : asset file already exists
At line:1 char:1
+ Submit-ACMECertificate test.mydomain.com-20171025
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMECertificate], IOException
    + FullyQualifiedErrorId : System.IO.IOException,ACMESharp.POSH.SubmitCertificate

PS C:\Users\Administrator> Update-ACMECertificate test.mydomain.com-20171025
Update-ACMECertificate : Certificate has not been submitted yet; cannot update status
At line:1 char:1
+ Update-ACMECertificate test.mydomain.com-20171025
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-ACMECertificate], Exception
    + FullyQualifiedErrorId : System.Exception,ACMESharp.POSH.UpdateCertificate

PS C:\Users\Administrator>

**Comment by ebekker** [comment]
Hmm, did you by any chance try to submit the cert earlier (the first time) but the operation didn't complete successfully or was manually aborted?  It looks like the Vault might be stuck in an intermediate/inconsistent state.

**Comment by ebekker** [comment]
If you just try to create a brand new cert (you can reference the same Identifier (DNS name)) and submit that, does that go through?

**Comment by meluvalli** [comment]
I was able to resolve it by creating a whole new one.   I don't know what happened though to cause this issue.

**Comment by kennethtipton** [comment]
In case it helps anyone else, i was getting this error even though I'm on Windows 10 Pro. If you are on a domain pc then check your default group policy and look for:

Computer Conifg > Windows Settings > Security Settings > Public Key Policies > Encrypting File System

If there is an expired certificate listed there you can just right click > create data recovery agent and select an admin account. A new certificate should be created and you can run gpupdate on your pc and re-run the 'Submit-ACMECertificate' with a new alias. Worked for me anyway.

from: martin-cdx commented on Dec 19, 2017
