### ISSUE TITLE
Unable to JSON parse revoke request

### ISSUE THREAD

**Issue by isaeed** [ebekker/ACMESharp#315]
i have installed the latest version ( 0.9.1.326 nuget version ) and trying the new Revoke method. but having follwoing error, please if anyone can guide me, what i am doing wrong. thanks 

Unexpected error
 +Response from server:
	+ Code: BadRequest
	+ Content: {
  "type": "urn:acme:error:malformed",
  "detail": "Unable to JSON parse revoke request",
  "status": 400
}

**Comment by WouterTinus** [comment]
I have the same error. I'm passing a base64-encoded string from contents of the .der file as created by the SaveCertificate() function of the CertificateRequest

**Comment by WouterTinus** [comment]
I used JwsHelper.Base64UrlEncode instead of standard .NET Base64 encoding and that fixed the issue for me.

**Comment by isaeed** [comment]
Thanks @WouterTinus , it fixed my issue also and i got OK response back.

**Comment by romarioj2h** [comment]
How you fixed the issue?

**Comment by isaeed** [comment]
hi @romarioj2h  , 
just follow @WouterTinus suggestion i.e. ( I have the same error. I'm passing a base64-encoded string from contents of the .der file as created by the SaveCertificate() function of the CertificateRequest )
