### ISSUE TITLE
tls-sni-01 usage example

### ISSUE THREAD

**Issue by pingec** [ebekker/ACMESharp#318]
According to https://github.com/ebekker/ACMESharp/pull/308 seems like tls-sni-01 is already in master thanks to @WouterTinus and @Marcus-L

Could we please get any examples added to the docs on how to use this challenge type in a poweshell script (with automated IIS and manually).

This would really help in those cases when port 80 is blocked...

**Comment by Marcus-L** [comment]
The change in #308 only implements tls-sni-01 capability in the ACMESharp API and I believe will spit out the info needed to complete the challenge manually via the powershell (I didn't test this though, I'm not familiar with the powershell tools). The code required to implement the challenge is non-trivial-- you have to generate a new temporary certificate using the challenge token, install the certificate into your certificate store, and then configure IIS to add a SNI binding with that certificate. Then ideally you'd wait for the challenge to be verified and then remove the binding and temporary certificate to clean up. You can see my code that [Certify](https://github.com/webprofusion/certify) uses to automate the tls-sni-01 challenge using the ACMESharp API here: https://github.com/webprofusion/certify/commit/191bfe6e715ec84b1b0820ded0bf3ce811bc6189
