### ISSUE TITLE
Artifacts for ACMESharp

### ISSUE THREAD

**Issue by amlynnworth** [ebekker/ACMESharp#33]
Previously, artifacts for people without visual studio were available at 
https://ci.appveyor.com/project/ebekker/letsencrypt-win/build/artifacts

What about for ACMESharp?  It is reasonable to expect them to become available?

(I am asking because I want to make AWS certificates, so the easy exe that works for IIS is not the answer.)

**Comment by ebekker** [comment]
After I renamed the project on GitHub, I renamed it in some of the integrations as well, so the code is still there, but the project was renamed, check [this out](https://ci.appveyor.com/project/ebekker/ACMESharp/build/artifacts).  BTW, the CI badge in the README in the master branch was already updated with this path.

**Comment by ebekker** [comment]
BTW, let me know how the AWS certs work out for you, I've been successful in generating a few via the closed BETA already for my own internal purposes, so hopefully will be useful for others as well.

**Comment by amlynnworth** [comment]
I'm downloading the artifacts now. Sorry, I tried to find them under the new project name and didn't manage earlier.

The AWS certs that I made in the last week, before the project rename, are not right yet.  I only just realized that some browsers (Firefox) give this error,

The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

(Error code: sec_error_unknown_issuer)
 <unknown>

( I should say that I made the cert chain myself and submitted it to AWS myself using aws cli because I wasn't completely clear how to do the last step with PowerShell. Maybe my problem is that I need more certs in my chain.   Is there some syntax that lets me write the correct cert chain to a disk file from your scripts? )

I am on the closed beta and it's also possible that I missed a POSH step for specifying the correct server.  I did not see a step or parameter for that in the example usage wiki.  The email from Let's Encrypt gave me a URL to use and some of the steps for running the ./letsencrypt-auto client include a -server parameter for the server api url.  How should I get that detail in, for use with ACMESharp?

I don't mind giving you a URL to test if that would help you to see one of my certs.  The ones I did for IIS are fine, it's only the AWS CloudFront ones that are not "

**Comment by amlynnworth** [comment]
After I do

Complete-ACMEChallenge -Ref $DNS1 -Challenge http-01 -ProviderConfig $ProviderID

I have to go onto my S3 bucket and change the ACL to public for the ./well-known/ acme-challenge/ file.  The parent folders are tagged public but the actual challenge file (the one with the very long "random" name) is never public.

This has been the case for all my tests, including just now using the latest files.
