### ISSUE TITLE
Command to query Vault for existing certificates

### ISSUE THREAD

**Issue by Arkans428** [ebekker/ACMESharp#367]
Hi,

I'm trying to find how if there is a way to query the ACME vault once created, on any existing aliases i may have used already or certificates i may have successfully requested? I created a cert three months ago, semi-following the guide (i inputted a different alias name rather than the guide) and i forgot what i used and now need to renew the cert. I will create a new one altogether as i have read you can request certificates using a different alias for the same domain ( https://github.com/ebekker/ACMESharp/issues/165 ) but in case there is a way, i just want to know how to do so in the future.

**Comment by chaami** [comment]
Hi,
Have you tried
```powershell
Set-ACMEVault -Baseservice "Your_Service_Name_Here"
Get-ACMECertificate
```
Kind regards.
