### ISSUE TITLE
Issue with ACME v2

### ISSUE THREAD

**Issue by narcis-mihai** [ebekker/ACMESharp#373]
Hi since let's encrypt went to acme v2 the registration does not work and I get this error: 

**New-ACMERegistration : Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that
supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.**

Any idea if there is another method to registre using ACMe v2?

**Comment by sparkyone1973** [comment]
Hi, I have the same issue, is there a workaround?
I'm trying to use https://github.com/intelequia/letsencrypt-aw/blob/master/letsencryptaw.ps1 to create a runbook for Azure automation.

**Comment by ebekker** [comment]
If you're looking for an ACME v2 compatible client library, please check out [ACMESharpCore](https://github.com/PKISharp/ACMESharpCore).

If you're looking for an ACME v2 compatible PowerShell module, please check out [ACMESharpCore-PowerShell](https://github.com/PKISharp/ACMESharpCore-PowerShell).
