### ISSUE TITLE
Upgrade powershell code to ACMEv2 protocol

### ISSUE THREAD

**Issue by haviay** [ebekker/ACMESharp#374]
Hi,
i use ACMESharp via power shell to create multiple domains per certificates
How can i rewrite this code below?

> import-module ACMESharp
> 
> $email = "mailto:admin@admin.com"
> $iissitename = "websitename"
> $certname = "aaa15$(get-date -format yyyy-MM-dd--HH-mm)"
> $pfxfile = "C:\Certs\03\pfx\$certname.pfx"
> 
> $initializevault = $FALSE
> $createregistration = $FALSE
> $createalias = $TRUE
> 
> 
> $domains = @(<...list of domains...>			
> 	)
> 
> $aliases = @()
> 
> 
> 
> 
> 
> if($initializevault) 
> {
>     Initialize-ACMEVault
> }
> 
> Get-ACMEVault
>

**Comment by ebekker** [comment]
If you wish to migrate your PWSH script(s) to ACMEv2 I recommend migrating to the excellent [ACME-PS](https://github.com/PKISharp/ACME-PS) library by @glatzert.
