### ISSUE TITLE
Possible to use with Kestral?

### ISSUE THREAD

**Issue by AraHaan** [ebekker/ACMESharp#375]
So I use asp.net core 3.1, I would like to be able to have my api automatically check for if the cert expires before issuing a new one to replace it.

Think this is possible?

**Comment by ebekker** [comment]
So you want to test to see if a cert is already expired?  Is that the challenge, inspecting the expiration date of the currently installed cert?

**Comment by AraHaan** [comment]
That and issuing a new one automatically to be used with Kestrel automatically without needing to restart it.

**Comment by ebekker** [comment]
Yes it's quite possible, but you would pby be more interested in the spin-off project [ACMESharpCore](https://github.com/PKISharp/ACMESharpCore) which is a .NET Standard-based version of an ACME client and specifically the [Kestrel example](https://github.com/PKISharp/ACMESharpCore/blob/master/src/examples/ACMEKestrel) that shows you how to do what you're asking about.

The _secret sauce_ is mostly in [this IHostedService](https://github.com/PKISharp/ACMESharpCore/blob/master/src/examples/ACMEKestrel/AcmeHostedService.cs) which handles the ACME interactions for obtaining certificates for the requested domain names.

Additionally, you need to configure a [custom service selector](https://github.com/PKISharp/ACMESharpCore/blob/master/src/examples/ACMEKestrel/AcmeExtensions.cs#L39) -- this delegates control of what certificate Kestrel uses for each connection to your own custom code logic.  And with that you can select any one of the previously available certificates (already issued by LE via the IHostedService) or any future certs that will be issued to replace expiring certs.  This is all dynamic so it would not require a restart of the Kestrel server to update a cert.
