### ISSUE TITLE
certifytheWeb is returned with this issue please help 

### ISSUE THREAD

**Issue by Medharf** [ebekker/ACMESharp#376]
Could not verify URL is accessible: http://remote.hhhh.com/.well-known/acme-challenge/configcheck

**Comment by ebekker** [comment]
CTW project is [here](https://github.com/webprofusion/certify).  CTW doesn't use ACMESharp anymore, it uses Certes.

CC: @webprofusion-chrisc

**Comment by webprofusion-chrisc** [comment]
Well, you know we might still use ACMESharp one day :)

**Comment by webprofusion-chrisc** [comment]
@Medharf please also see https://community.certifytheweb.com/ for general community support.
