### ISSUE TITLE
Maintenance State

### ISSUE THREAD

**Issue by weldrake13** [ebekker/ACMESharp#379]
Hi, 

Please could you confirm if this project is actively maintained still?

I don't see any active issues outstanding but the latest commit was some time ago. 

Thanks! 

:)

**Comment by weldrake13** [comment]
Found the acmesharp core repo, which i think is the same maintainers but actually what I am looking for! :)

**Comment by ebekker** [comment]
Yes, the PKISharp/ACMESharp repo is the successor to this project with .NET Core compatibility.
