### ISSUE TITLE
CertificateProvider TargetInvocationException

### ISSUE THREAD

**Issue by DanielBrownAU** [ebekker/ACMESharp#41]
When running:

New-ACMECertificate -Identifier $webalias -Alias $certalias -Generate
Submit-ACMECertificate -Ref $certalias

I get the following:

Submit-ACMECertificate : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ Submit-ACMECertificate -Ref $certalias
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMECertificate], TargetInvocationException
    + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,ACMESharp.POSH.SubmitCertificate

I have narrowed it down to 
ACMESharp-master\ACMESharp\ACMESharp\PKI\CertificateProvider.cs, Line 148

Code:
            return (CertificateProvider)t.GetConstructor(PROVIDER_CTOR_SIG)
                    .Invoke(new[] { initParams });

**Comment by ebekker** [comment]
@DanielBrownAU, do you know if you still encounter this exception with the latest release?

I'm going to close this ticket for now, I believe you shouldn't get this anymore, but I'll reopen if that's not the case.

Also, can you detail your environment and parameters (e.g, OS version, PS version, which CertProvider you're using, any special params to any of the providers, etc.).

Thanks.
