### ISSUE TITLE
Join Twitter

### ISSUE THREAD

**Issue by bitcrazed** [ebekker/ACMESharp#44]
With no email, blog or Twitter handle listed on your account, it's kinda hard to ping you :telephone_receiver: 

Perhaps this was intentional? :grinning: 

Either way, it'd be great if you could create a Twitter account (and state it on your profile page) so that I and others who are interested in what you're doing with AcmeSharp can ping you (only) when necessary!

Many thanks :+1:

**Comment by ebekker** [comment]
You can ping me on gitter, link is on the project readme, I set it up just for this project.

Please use that for 'real time' kind of questions as it integrates nicely with github.
