### ISSUE TITLE
Unable to resubmit challenge that has failed

### ISSUE THREAD

**Issue by johnmannix** [ebekker/ACMESharp#49]
If I use Submit-ACMEChallenge and it fails for some reason - say the validation file wasn't available on the expected URL - then I want to be able to fix the problem and re-submit the validation.

However, if I try to do that I get an "Unexpected error" from Submit-ACMEChallenge.

I have tried calling Complete-ACMEChallenge with -Regenerate and/or -Repeat but neither seem to resolve this problem.

**Comment by ebekker** [comment]
That's actually a limitation of the Let's Encrypt service.  I don't think it's explicitly documented to addressed in the ACME specification, but when a Challenge is first issued, it's in the `pending` state, then when you submit the Challenge (after you've handled it), and the ACME server tries to validate it, if it succeeds, the Challenge moves to the `valid` state, and if not, then it moves to the `invalid` state.  Once the Challenge state has changed, you cannot resubmit it again.  You have to resubmit the whole Identifier Validation again.

So unfortunately, nothing I can do about that.

**Comment by ebekker** [comment]
One thing I will do though, is improve the user experience by detecting the situation and messaging better guidance, as documented in [this new ticket](../50).

**Comment by johnmannix** [comment]
In that case, is there a way to delete an identifier so that you can start again?
