### ISSUE TITLE
Add ability to specify file path for Manual provider

### ISSUE THREAD

**Issue by nul800sebastiaan** [ebekker/ACMESharp#52]
Right now, doing `New-ACMEProviderConfig -WebServerProvider Manual` will pop up a notepad instance just so you can optionally provide a path to a file. Would be good to have an option to provide the file path in `New-ACMEProviderConfig` so that this can be completely automated.

I've looked at the code a bit but I'm not entirely sure where to add it, with some pointers I'd be happy to help out and send a PR.

**Comment by ebekker** [comment]
I agree, it's really just a stopgap solution right now, and as you say it doesn't work for a completely automated solution.

I can switch it to use a flag to either *enable* editing, instead of making it the default, or provide an option to use a preexisting, pre-configured config file, instead of generating a default from template.

**Comment by nul800sebastiaan** [comment]
I played some more and I'm not even sure why you'd need to store this file, the data is already available from the Complete-ACMEChallenge call and gets stored in the vault, [I just blogged about my experiments](https://cultiv.nl/blog/lets-encrypt-on-windows/), see how I get the challenge key/value there? Don't even use the outputted file :)

**Comment by ebekker** [comment]
The ProviderConfig mechanism is now gone with the latest release, it has been replaced with Challenge Handler Profiles if you still need similar functionality, or simply *inline* parameters when handling a Challenge.

This was completed as part of the change for cleaning up the providers model.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.

I'm going to close this for now.  If this still doesn't address your concerns or request, reopen and let's discuss.
