### ISSUE TITLE
Issue with extensionless static file mapping in IIS

### ISSUE THREAD

**Issue by johnmannix** [ebekker/ACMESharp#55]
I found that I had to modify the extensionless file mapping in the web.config file in order to get IIS to serve the challenge file. The change I made was to remove the asterisk from the extension in the mapping - so I changed to the following:

```
<staticContent>
    <mimeMap fileExtension="." mimeType="text/json" />
</staticContent>
```

The letsencrypt simple project regenerates the web.config every time it runs, so to make this change I had to add the mapping above in the root web.config.

This was on IIS7.5 on Windows Server 2008 R2.

**Comment by ebekker** [comment]
I've incorporated the fix into the `cleanup-providers` branch, so that will address this issue as soon as it's merged in.

**Comment by sebastienfi** [comment]
You should check that : https://github.com/Lone-Coder/letsencrypt-win-simple/issues/37

**Comment by ebekker** [comment]
The IIS Challenge Handler is spitting out a local web.config that seems to do the trick in all the tests I've run.  Please try the latest release and confirm it addresses your issue.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.

I'm closing this for now, if this does not address your issue, please reopen and let's discuss.

**Comment by johnmannix** [comment]
Thanks for the update. I'll check when I get a chance and will you know if there are any problems.
