### ISSUE TITLE
Leaking temp files

### ISSUE THREAD

**Issue by willdean** [ebekker/ACMESharp#58]
I've noticed at least one place (`EditProviderConfig.ProcessRecord`) where a `GetTempFileName` file isn't removed after use.  Would you be interested in a PR to deal with tiding up tempfiles?

**Comment by ebekker** [comment]
Sure, thanks!

**Comment by willdean** [comment]
I actually think this was about the only instance.  Elsewhere there are generally try/finally blocks with explicit deletes in the finally clause.  

I normally handle temp files by having a very simple disposable class which wraps the `GetTempFileName` call and deletes the file when it's disposed.  Would you prefer this approach, or would you prefer to stick to explicit `try/finally`?

**Comment by ebekker** [comment]
Let's go with your idea, you can put a utility class in the Util namespace in the main assembly.  If you feel adventuresome, you can convert all instances of temp file usage to use this pattern through out the solution.

**Comment by willdean** [comment]
OK, I've put in a PR just for the wrapper class and the one fix - if you're happy with this, I'll do the others.
