### ISSUE TITLE
Implement latest ACME spec changes

### ISSUE THREAD

**Issue by ebekker** [ebekker/ACMESharp#6]
Need to update the client with the latest changes to the ACME spec:

Add explicit versioning to challenges
* [ietf-wg-acme/acme/pull/6](https://github.com/ietf-wg-acme/acme/pull/6) - Address signature reuse vulnerability
* [ietf-wg-acme/acme/pull/7](https://github.com/ietf-wg-acme/acme/pull/7) - Address default virtual host risks
* [ietf-wg-acme/acme/pull/8](https://github.com/ietf-wg-acme/acme/pull/8) - Add explicit versioning to challenges
* [ietf-wg-acme/acme/pull/13](https://github.com/ietf-wg-acme/acme/pull/13) - Use a deterministic value for validation

**Comment by ebekker** [comment]
Similar to updates made to the official client in https://github.com/letsencrypt/letsencrypt/issues/914

**Comment by qgustavor** [comment]
I'm getting this error and I think it's related to this issue:

    {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: Challenge data was corrupted"}

**Comment by ebekker** [comment]
@qgustavor, which challenge were you trying, I assume it's the HTTP response.  I have updated the client support the newer HTTP challenge type, but the older ```simpleHttp``` is still in there.  However, the Boulder CA may no longer be accepting it, if it's been updated to only work with what's in the latest version of the ACME spec.

Try to use the newer ```http-01``` challenge type, and let me know if that's still failing.

**Comment by qgustavor** [comment]
@ebekker It now worked. Seems it's time to update Example Usage, not only this but also some commands which got renamed and maybe other changes which I don't noticed.

**Comment by ebekker** [comment]
Additional spec change to implement:  https://github.com/ietf-wg-acme/acme/pull/56

**Comment by ebekker** [comment]
All changes to the spec, including updates to the supported Challenge Types have been incorporated and validated.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.
