### ISSUE TITLE
Simplification opportunity in NewProviderConfig.ProcessRecord?

### ISSUE THREAD

**Issue by willdean** [ebekker/ACMESharp#60]
While looking at extending the use of the TemporaryFile wrapper, I was pondering a bit of refactoring in   NewProviderConfig.ProcessRecord.

This contains the following code:

    var output = JsonConvert.SerializeObject(config);
    s = new MemoryStream(Encoding.UTF8.GetBytes(output));
    using (var fs = new FileStream(temp, FileMode.Create))
    {
        s.CopyTo(fs);
    }  

Is there any reason not to replace this with:

    File.WriteAllText(temp, JsonConvert.SerializeObject(config));

**Comment by ebekker** [comment]
Missed this ticket, sorry for the delay.  It looks like there used to be something in between some of those lines that got removed and of course it can be simplified even further to your example, yes.

However, this class (the NewProviderConfig cmdlet) has actually been removed in my working branch and that will shortly be merged to master, so it won't matter much shortly anyway.

Thanks for catching this -- let me know if you find anything else!
