### ISSUE TITLE
Challenge not comple

### ISSUE THREAD

**Issue by Trapulo** [ebekker/ACMESharp#61]
I tried to run it on two different servers (W2012 and W2012 R2). I cannot complete challenge.

If I use Certify GUI, it reports "challenge not yet completed check that http:/... is present and accessible". I checked the url and is OK, file is accessible.

I also tried direct from powershell, but still I cannot complete challenge.
Any idea?

thanks

**Comment by sebastienfi** [comment]
Can you provide the log file ?

**Comment by Trapulo** [comment]
Sorry, I uninstalled and now using an other solution....

**Comment by ebekker** [comment]
This sounds like it might be a problem specific to Certify, which has it's own [repo](https://github.com/webprofusion/Certify).

If anyone still has this issue, it's pby best to open an issue ticket in that project.

Closing this ticket for now.
