### ISSUE TITLE
Could not submit certificate request on production service

### ISSUE THREAD

**Issue by MichaelPetrinolis** [ebekker/ACMESharp#62]
Hi, I get the following error when try to submit a certificate request on production.

ACMESharp.AcmeClient+AcmeWebException: Unexpected error ---> System.Net.WebException: 
Remote Server return an error: (429) Unknown.
   at System.Net.HttpWebRequest.GetResponse()
   at ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message) at C:\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:line 576
   σε ACMESharp.AcmeClient.RequestCertificate(String csrContent) at C:\ACMESharp\ACMESharp\ACMESharp
\AcmeClient.cs:line 449
   at ACMESharp.POSH.SubmitCertificate.ProcessRecord() at C:\ACMESharp\ACMESharp\ACMESharp.POSH\SubmitCertificate.cs:line 136

Some days ago, the production server worked. I don't get this exception on STAGING environment.
Is something broken?

**Comment by ebekker** [comment]
Nothing has changed in this project recently, but I will try it out and confirm as soon as I get a chance. It might be something broke temporarily in the LE server, maybe give it another try after some time.

**Comment by MichaelPetrinolis** [comment]
Thanks, I will close the issue as the 429 means too many requests. So I have probably hit the rate limits while developing my posh scripts. 
That's the reason it is working on Staging environment. No need to waste your time.

**Comment by ebekker** [comment]
Thanks for the follow up.

One of the enhancements that's been talked about is interpreting some of the error responses and providing additional details about what might be the cause -- this looks like a good candidate.
