### ISSUE TITLE
Getting Chain Certificate for Apache 2.4

### ISSUE THREAD

**Issue by jlcastillo** [ebekker/ACMESharp#66]
I use the following line to get my certificates after a successful ACME challenge:

  Get-ACMECertificate -Ref cert1 -ExportKeyPEM cert1-key.pem -ExportCertificatePEM cert1-crt.pem

However I don't know how to feed Apache with them, as it needs 3 files:

  SSLCertificateFile <path_to>/cert.pem
  SSLCertificateKeyFile <path_to>/privkey.pem
  SSLCertificateChainFile <path_to>/chain.pem

At this moment, my browser detects a non-trusted certificate issued by "happy hacker fake CA" (BTW a terrible name if you ask me...).

**Comment by ebekker** [comment]
The command you have will produce the `/privkey.pem` file and the `/cert.pem` file.

Additionally, you need to use `Get-ACMEIssuerCertificate` and pass it the serial number of the signer that generated your certificate (which you can see just by doing a Get-ACMECertificate with no export options).

**Comment by jlcastillo** [comment]
Eureka!  I'll write a small tutorial and provide my scripts in a few days.

Thanks @ebekker for your support.
