### ISSUE TITLE
Review comments from Chocolatey package submission

### ISSUE THREAD

**Issue by ebekker** [ebekker/ACMESharp#70]
These are the comments from @ferventcoder after reviewing the first choco package submission:

> During uninstall you may want to just search both directories and remove. You may have an opportunity that the user may install as a non-admin and then later run the uninstall as an admin or vice versa.
>
> This will qualify as a trusted package as you are also the software author, but we'll want to go through a couple of package approvals first.
>
> This package uses all kinds of POSH v3 in it. For the chocolateyInstall/Uninstall scripts, we typically ask for them to be compatible with POSH v2. This does present a conundrum when POSH modules are v3 - so what we ask is that folks check the version of POSH in the beginning and fail early on the package install. Then add it to the description here somewhere that this is v3+.
>
> If you can add the check and fail at the very least to the chocolateyInstall.ps1, I will approve this package. Please resubmit this same version. Thanks!

**Comment by ebekker** [comment]
Both suggestions have been incorporated.

**Comment by ferventcoder** [comment]
:+1:

**Comment by ferventcoder** [comment]
@ebekker I just noted a couple of things on your last commit - thoughts on that?

**Comment by ebekker** [comment]
I responded -- not sure if you got notifications.
