### ISSUE TITLE
ManualWebServer provider and FilePath Empty

### ISSUE THREAD

**Issue by Elvinra** [ebekker/ACMESharp#8]
Hi,

File ManualWebServerProvider.cs

Line 21 : path = Path.GetTempFileName();

Include the documentation of Microsoft, this method create a tmp file

but 

Line 29 : using (var fs = new FileStream(path, FileMode.CreateNew))

Include the documentation of microsoft, the enumeration FileMode.CreateNew throw a exception if the file exists and in this case the file already exists and a exception is throw.

**Comment by ebekker** [comment]
This issue was addressed as a side effect of refactoring the Vault stuff to support assets.
