### ISSUE TITLE
SAN names not working

### ISSUE THREAD

**Issue by JamieB226** [ebekker/ACMESharp#86]
I am trying to use the AlternativeIdentifierRefs parameter to New-ACMECertificate to request a SAN Certificate.  I have completed the challenges for all the individual names and they show valid.  When I run New-AcmeCertificate, I get the error below:

PS > New-ACMECertificate Primary -Generate -Alias Primary -AlternativeIdentifierRefs san1
New-ACMECertificate : Cannot bind parameter 'AlternativeIdentifierRefs'. Cannot convert the "san1" value of type
"System.String" to type "System.Collections.Generic.IEnumerable`1[System.Object]".
At line:1 char:81
+ ... cate Primary -Generate -Alias Primary -AlternativeIdentifierRefs san1
+                                                                      ~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-ACMECertificate], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,ACMESharp.POSH.NewCertificate

**Comment by ebekker** [comment]
@JamieB226, the argument to the refs parameter is actually a string array.  Normally, a single string will be automatically converted to a single-element array, but not sure why it's not working for you (which version of PowerShell are you using?  Inspect $PSVersionTable).

So to force the correct parameter, instead of specifying a lone ref name, specify it as `,san1` -- the leading comma will force PS to treat it as a string array.

**Comment by JamieB226** [comment]
That was what I needed.  I was converting the array back to a string (comma joined).  It works correctly with the array.  Thanks for your help.

**Comment by dynamite-ready** [comment]
> So to force the correct parameter, instead of specifying a lone ref name, specify it as ,san1 -- the leading comma will force PS to treat it as a string array.

This did not work for me.
My Powershell version table reads as:

Maj: 5, 
Min: 0, 
Build: 10514, 
Rev: 6

Any other suggestions?

**Comment by JamieB226** [comment]
Try:

$sanarray=@()
$sanarray+=“san1”
$sanarray+=“san2”
…
$sanarray+=“sanN”

and then pass $sanarray as the parameter.

**Comment by dynamite-ready** [comment]
Thank you. I'm new to Powershell, so that's an eye opener.

**Comment by plitter** [comment]
I was having the same issue. I only had www subdomain to add to the certificate and tried the , putting it in array $array = @("<domain>") and it didn't work. But $array = @("<domain>", "<domain>") did :) lets encrypt removes duplicates it seems :)
