### ISSUE TITLE
Submit-ACMECertificate failed (Remove/Delete ACMECertificate)

### ISSUE THREAD

**Issue by Xyanid** [ebekker/ACMESharp#89]
I tried to issue serveral certificates for my site and each subdomain I own, in total this makes 6 Certificates for which I create 12 ACMEIdentifier.

Each certificate contains the main ACMEIdentifier plus another ACMEIdentifier as a AlternativeIdentifierRefs. I successfully issued two ACMECertificates this way. However when I tried to submit the third ACMECertificate I got an error message, saying that too many Certificates have already been issued for my main domain.

After that error message I closed my Powershell, then I restarted the Module and tried to submit the failed submit for the certificate again. This however did not work as I got the following error message.

Submit-ACMECertificate : asset file already exists
At line:1 char:1
+ Submit-ACMECertificate sub.domain.de_Certificate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMECertificate], IOException
    + FullyQualifiedErrorId : System.IO.IOException,ACMESharp.POSH.SubmitCertificate

Listing the ACMECertificates with Get-ACMECertificate showed that the certificate exists, so now I can not create a new one with the same name. 

I think it would be good to removed/delete ACMECertificates otherwise I will not be able to clear the vault of ACMECertificates I no longer need.

The other question is, what is the limitation to issuing certificates, can I only issue two certificates per domain regardless of sub domain?

**Comment by bseddon** [comment]
There is a [limit imposed by Let's Encrypt](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769) of 5 certificates for a domain in a 7 day period. It is hoped this limit will be removed, or at least raised, when the public beta ends and the service becomes final.  However, any one certificate can include up to 100 ASNs so its not too bad.

The message "asset file already exists" is one from the Let's Encrypt servers and appears when a certificate submission failed because the certificate limit has been reached.  I've see this also and when I searched for the term I see users of the Linux client also receive the message.

I don't think you can do much but wait it out.

**Comment by Xyanid** [comment]
Well that is good to know, thanks. I think this issue is resolved then,

**Comment by bseddon** [comment]
I'm revisiting my response to your question as my response is not correct.  The message 'asset file already exists' is generated by the ACMESharp Vault provider.  The solution is to remove four files from the vault.

You can see where the vault is located by issuing the PowerShell command:
```
(Get-ACMEVaultProfile).VaultParameters['RootPath']
```
Under this folder there will be a number of sub-folders.  The task is to delete one file from each of four sub-folders.  The sub-folders are: '40-KEYGN', '45-KEYPM', '50-CSRGN' and '55-CSRPM'.

The files will have different names but will all begin with the same 36 characters.  These characters are the 'id' (not alias) of the certificate you are trying to submit.  To retrieve the id and if the certificate alias is 'certalias' the PowerShell command to display the id is:
```
(Get-ACMECertificate $certalias).Id
```

**Comment by ebekker** [comment]
FYI, the limits for LE during beta has been raised from 5 to 20 certs per domain per week.

I think this issue has been addressed with @bseddon's comments, so closing for now.
