### ISSUE TITLE
manualDnsServerProvider

### ISSUE THREAD

**Issue by Elvinra** [ebekker/ACMESharp#9]
hi,

I was generated a ManualDnsServer Config file and i was changed the DefaultDomain by my domain name, ben when a complete-ACMEChallenge i have that error :

Complete-ACMEChallenge : Specified argument was out of the range of valid values.

the format of my domain name is like google.fr

**Comment by qgustavor** [comment]
Same error happening here. I don't know if it's related but Example Usage only provides a example configuration file for AwsS3 provider, so other providers are a bit harder to understand. From the source code I was expecting [this line](https://github.com/ebekker/letsencrypt-win/blob/1f3b92ec405442f691f9edf4b1498b681d2e26ae/letsencrypt-win/LetsEncrypt.ACME/DNS/ManualDnsProvider.cs#L30) to be shown, not the error showed above.

**Comment by qgustavor** [comment]
Correct me if I'm wrong, but seems `ManualDnsProvider` isn't implemented: `DefaultDomain` is only used in unit tests.

**Comment by ebekker** [comment]
@Elvinra / @qgustavor, sorry, I somehow missed this issue over the last 27 days!

Anyway, I suspect the issue you're running into is that the Let's Encrypt folks decided to defer support of the DNS-based challenges till after the official release of LE to the public and the 1.0 release of the Boulder CA.  So even though they still define the challenge type in the ACME spec, they're not implementing or supporting it in Boulder till it's better fleshed out.

So, before they cut that off, I was running tests against their STAGE server and it was successful, but then they dropped those challenges and it was no longer an option.  We'll have to circle back around to this issue after they re-introduce it in their API.

**Comment by ebekker** [comment]
The DNS challenge support has been restored to the LE staging server and I've run some tests and confirmed it's working once again for ACMESharp as well.

**Comment by ebekker** [comment]
The DNS Challenge Type has been restored and tested against staging.

Both `manual` and `awsRoute53` providers support this.

This was completed as part of the change for cleaning up the providers model.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.
