### ISSUE TITLE
Handle JSON parse Exception if response is not JSON.

### ISSUE THREAD

**Issue by c0bra99** [ebekker/ACMESharp#92]
I was trying to run letsencrypt-win-simple on my IIS webserver, and it kept crashing with this error:
```
[Error] Error JsonReaderException { LineNumber: 0, LinePosition: 0, Path: "", Message: "Unexpected character encountered while parsing value: <. Path '', line 0, position 0.", Data: [], InnerException: null, TargetSite: Boolean ParseValue(), StackTrace: "   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at ACMESharp.AcmeClient.GetDirectory(Boolean saveRelative)
   at LetsEncrypt.ACME.Simple.Program.Main(String[] args)", HelpLink: null, Source: "Newtonsoft.Json", HResult: -2146233088 }
```

It ends up being that inside of AcmeClient.GetDirectory, if the resp.ContentAsString is not JSON it throws the rather generic exception. In my case I believe it was an issue with my network setup (Proxy/IDS/etc) causing an "Access is denied" to be returned instead of a JSON response. It seems there is not a lot of error handling in this method, adding something as simple as showing the response content and the URL to the exception could have helped resolve the issue without having to step through source code.

Related issue: https://github.com/Lone-Coder/letsencrypt-win-simple/issues/117

**Comment by rkerber** [comment]
While testing tonight, I ran into this with when using https://acme-staging.api.letsencrypt.org/, but https://acme-v01.api.letsencrypt.org/ worked just fine for me. So they must be doing something with the staging API.

**Comment by ebekker** [comment]
Actually, the content and details of the request/response are available in the Exception (it's a standard .NET base class WebException that has all the details that originated the exception).  Even if I did add more details of my own to the ACMESharp library code, it wouldn't help you unless the client that you're using surfaces it, either in the UI or some other mechanism (e.g. console, logs, etc.).

If you have any more suggestions of how to expose the details, I'll be happy to consider them.  Or if you want to enhance the logic with specifics, feel free to submit a PR.

**Comment by ebekker** [comment]
I'm going to close the issue for now, if you have further suggestions or want to discuss more, please reopen.
