### ISSUE TITLE
Non-CNG Private Keys

### ISSUE THREAD

**Issue by philpie** [ebekker/ACMESharp#93]
Is it possible to generate a certificate with a Non-CNG private key

**Comment by ebekker** [comment]
You can generate a private key pair and a CSR separately from the ACMESharp tools and simply import them when you submit the certificate request.  The in-built mechanisms use a provider model for delegating all PKI functions and default provider is based on the Windows-ported OpenSSL library.  But you can substitute your own provider if you are so inclined.

There is also support for an OpenSSL CLI interface and anything with a compatible CLI interface can be substituted.  Additionally, work was started on a more Windows-native provider implementation, but it's not a high priority for me and I was seeking community help to further that along.

**Comment by ebekker** [comment]
Closing for now, reopen if you have further questions or want to continue the discussion.
