### ISSUE TITLE
Error: Issuance for IP addresses not supported

### ISSUE THREAD

**Issue by shadi1024** [ebekker/ACMESharp#94]
I tried to create an SSL for IP address,
using the command:
` New-ACMEIdentifier -Dns xx.xx.xx.xx -Alias dns1`
where xx.xx.xx.xx is an ip address
I got the error: Issuance for IP addresses not supported

The question is: will SSL for ip addresses be supported by ACMESharp or is it a "let's encrypt" matter? Thanks for the great modules.

**Comment by bseddon** [comment]
The message is reporting a Lets Encrypt server response.  Let's Encrypt has decided that certificates will not be issued to IP addresses.  See this community discussion:

https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082

**Comment by shadi1024** [comment]
Thanks for your satisfactory response.
Again I would like to thank you for the great modules.
With regards,
