### ISSUE TITLE
Initialize-ACMEVault -BaseUri https://acme-v01.api.letsencrypt.ord/

### ISSUE THREAD

**Issue by arpitajoshi** [ebekker/ACMESharp#95]
Wrong initialization of baseURI
Now not able to go to next step

How can I change the -BaseURI now?

**Comment by bseddon** [comment]
Have you tried:

Set-ACMEVault -BaseUri https://acme-v01.api.letsencrypt.org/

**Comment by ebekker** [comment]
You can also use `-BaseService` option to specify one of the pre-defined service URL's by user-friendly name.
