### ISSUE TITLE
Get challenge info automaticaly

### ISSUE THREAD

**Issue by Alaanor** [ebekker/ACMESharp#97]
Hi, I'm not a master with powershell, I want to build a ps script for auto-renew the certificate.

There is only one thing that block me: get the fileContent from the Complete-ACMEChallenge output.

See this:
```
PS C:\www\myTests\letsEncrypt> $outputChallenge = Complete-ACMEChallenge myAlias -ChallengeType http-01 -Handler manual
== Manual Challenge Handler - HTTP ==
  * Handle Time:      [15.02.2016 13:57:37]
  * Challenge Token:  [###########################################]
To complete this Challenge please create a new file
under the server that is responding to the hostname
and path given with the following characteristics:
  * HTTP URL:     [############################################################################################]
  * File Path:    [######################################################################]
  * File Content: [#######################################################################################]
  * MIME Type:    [text/plain]
------------------------------------
PS C:\www\myTests\letsEncrypt>
```
Note: All information has been replaced by `#`

I though when you do something like that `$outputChallenge = Complete-ACMEChallenge myAlias -ChallengeType http-01 -Handler manual` You get all the output into the $ouputChallenge variable.

Now the variable contains only a part of the output... which is:
```
PS C:\www\myTests\letsEncrypt> echo $outputChallenge
IdentifierPart : ACMESharp.Messages.IdentifierPart
IdentifierType : dns
Identifier     : #########
Uri            : #####################################
Status         : pending
Expires        : 22.02.2016 12:57:28
Challenges     : {manual, , }
Combinations   : {0, 1, 2}
PS C:\www\myTests\letsEncrypt>
```

How to get the `* File Content: ` content ? I'm not able to catch him.

Thank for any help, and, of course, if there isn't the place for asking this, sorry :/

Alaanor.

**Comment by bseddon** [comment]
I created a script to create/renew certificates in one command.  You can find it in [issue 76 ](https://github.com/ebekker/ACMESharp/issues/76#issuecomment-174705344)

You can either use it or compare what you are doing with what it does to see how to make progress.

**Comment by Alaanor** [comment]
Yeah, but the problem of your script is that work only with IIS (local certificate), I'm running apache on Windows (What a strange configuration !)

Maybe I am wrong, say me in this case. But in any case, I will inspect one more time your script :)

**Comment by bseddon** [comment]
You are right, it will not work for you.  However, it will show you how to resolve your problem because it successfully completes the certificate generation step and saves the certificate to a file.  It uses the ExportPKcs12 option but you can use the option to export a .pem file instead.

**Comment by ComDAC** [comment]
Just today I figured this out. Here is the code I used:

```
$chalProps = (Complete-ACMEChallenge $alias -ChallengeType http-01 -Handler manual)
$chal = $chalProps.Challenges | Where { $_.Type -eq 'http-01' }
```

Then you can get the File Contents and Token with the following:
```
$chal.Challenge.FileContent
$chal.Challenge.Token
```

Remember to specifiy the appropriate challenge type in the where statement.

**Comment by ebekker** [comment]
Hopefully, everyone's questions have been answered so I'm closing.  If not, please reopen or continue the discussion.
